global:
  env:
    'Logging__LogLevel__Default': 'Information'
    'Logging__LogLevel__Microsoft.EntityFrameworkCore': 'Warning'
    'Logging__LogLevel__Microsoft.AspNetCore': 'Warning'
    'Logging__LogLevel__StrDss.Common.StrDssLogger': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Staging'
    'ENV_NAME': 'uat'
    'APP_BASE_URL': 'https://uat.strdata.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://dev.loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches-test.api.gov.bc.ca'
    'RENTAL_LISTING_REPORT_MAX_SIZE': '4'
    'BCEID_URL': 'https://gws1.test.bceid.ca/webservices/client/v10/bceidservice.asmx'
    'BCEID_CACHE_LIFESPAN': '600'

nameOverride: strdss-uat
fullnameOverride: strdss-uat

route:
  host: uat-strdata.apps.silver.devops.gov.bc.ca
  baseService: strdss-uat

frontend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-uat-frontend
  fullnameOverride: strdss-uat-frontend
  secretName: strdss-secrets-uat

  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 50Mi

  env:
    'API_HOST': '/api'

  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}    

backend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-uat-backend
  fullnameOverride: strdss-uat-backend
  secretName: strdss-secrets-uat
  dbSecretName: strdssuat-pguser-strdssuat
  crunchydb: true

  # resources:
  #   limits:
  #     cpu: 1500m
  #     memory: 1500Mi
  #   requests:
  #     cpu: 20m
  #     memory: 1100Mi

  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 20m
      memory: 200Mi

  env:
    'API_HOST': '/api'
    
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}    
