global:
  vault:
    role: f4a30d-prod
    subPath: strdss-prod
  env:
    'Logging__LogLevel__Default': 'Warning'
    'Logging__LogLevel__StrDss.Common.StrDssLogger': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Production'
    'ENV_NAME': 'prod'
    'APP_BASE_URL': 'https://strdata.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logon7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches.api.gov.bc.ca'
    'RENTAL_LISTING_REPORT_MAX_SIZE': '10'
    'BCEID_URL': 'https://gws1.bceid.ca/webservices/client/v10/bceidservice.asmx'
    'BCEID_CACHE_LIFESPAN': '600'
    'GEOCODER_URL': 'https://geocoder.api.gov.bc.ca'

nameOverride: strdss-prod
fullnameOverride: strdss-prod

route:
  host: prod-strdata.apps.silver.devops.gov.bc.ca
  baseService: strdss-prod

frontend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-prod-frontend
  fullnameOverride: strdss-prod-frontend
  secretName: strdss-secrets-prod

  resources:
    limits:
      cpu: 30m
      memory: 140Mi
    requests:
      cpu: 20m
      memory: 70Mi

  env:
    'API_HOST': '/api'

  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}

backend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-prod-backend
  fullnameOverride: strdss-prod-backend
  secretName: strdss-secrets-prod
  dbSecretName: strdssprod-pguser-strdssprod
  crunchydb: true

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 300Mi

  env:
    'API_HOST': '/api'

  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}

hangfire:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-prod-hangfire
  fullnameOverride: strdss-prod-hangfire
  secretName: strdss-secrets-prod
  dbSecretName: strdssprod-pguser-strdssprod
  crunchydb: true

  resources:
    limits:
      cpu: 400m
      memory: 600Mi
    requests:
      cpu: 200m
      memory: 400Mi

  env:
    'API_HOST': '/api'

  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}            