global:
  vault:
    role: f4a30d-nonprod
    subPath: strdss-uat
  env:
    'Logging__LogLevel__Default': 'Warning'
    'Logging__LogLevel__StrDss.Common.StrDssLogger': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Staging'
    'ENV_NAME': 'uat'
    'APP_BASE_URL': 'https://uat.strdata.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://test.loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://test.loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches-test.api.gov.bc.ca'
    'RENTAL_LISTING_REPORT_MAX_SIZE': '30'
    'BCEID_URL': 'https://gws1.test.bceid.ca/webservices/client/v10/bceidservice.asmx'
    'BCEID_CACHE_LIFESPAN': '600'
    'GEOCODER_URL': 'https://geocodertst.api.gov.bc.ca'
    'ADDRESS_SCORE': '90'
    
nameOverride: strdss-uat
fullnameOverride: strdss-uat

route:
  host: uat-strdata.apps.silver.devops.gov.bc.ca
  baseService: strdss-uat

frontend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-uat-frontend
  fullnameOverride: strdss-uat-frontend
  secretName: strdss-secrets-uat

  resources:
    limits:
      cpu: 30m
      memory: 140Mi
    requests:
      cpu: 20m
      memory: 70Mi

  env:
    'API_HOST': '/api'

  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}    

backend:
  enabled: true
  replicaCount: 2
  nameOverride: strdss-uat-backend
  fullnameOverride: strdss-uat-backend
  secretName: strdss-secrets-uat
  dbSecretName: strdssuat-pguser-strdssuat
  crunchydb: true

  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 300Mi

  env:
    'API_HOST': '/api'
    
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}    

hangfire:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-uat-hangfire
  fullnameOverride: strdss-uat-hangfire
  secretName: strdss-secrets-uat
  dbSecretName: strdssuat-pguser-strdssuat
  crunchydb: true

  resources:
    limits:
      cpu: 200m
      memory: 600Mi
    requests:
      cpu: 100m
      memory: 400Mi

  env:
    'API_HOST': '/api'
    
  affinityTemplate: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels: {{ include "app.selectorLabels" . | nindent 10 }}    