global:
  env:
    'LOGGING__LOGLEVEL__DEFAULT': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Staging'
    'ENV_NAME': 'uat'
    'AppBaseUrl': 'https://uat-strdata.apps.silver.devops.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://dev.loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches-dev.api.gov.bc.ca'

nameOverride: strdss-uat
fullnameOverride: strdss-uat

route:
  host: uat-strdata.apps.silver.devops.gov.bc.ca
  baseService: strdss-uat

frontend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-uat-frontend
  fullnameOverride: strdss-uat-frontend
  secretName: strdss-secrets-uat

  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 50Mi

  env:
    'API_HOST': '/api'

backend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-uat-backend
  fullnameOverride: strdss-uat-backend
  secretName: strdss-secrets-uat
  dbSecretName: strdssuat-pguser-strdssuat
  crunchydb: true

  # resources:
  #   limits:
  #     cpu: 1500m
  #     memory: 1500Mi
  #   requests:
  #     cpu: 20m
  #     memory: 1100Mi

  resources:
  limits:
    cpu: 200m
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 100Mi

  env:
    'API_HOST': '/api'
