global:
  env:
    'LOGGING__LOGLEVEL__DEFAULT': 'Error'
    'LOGGING__LOGLEVEL__AWP': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Development'
    'ENV_NAME': 'dev'
    'AppBaseUrl': 'https://dev-strdss.f4a30d-dev.apps.silver.devops.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://dev.loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches-dev.api.gov.bc.ca'

nameOverride: strdss-dev
fullnameOverride: strdss-dev

route:
  host: dev-strdss.f4a30d-dev.apps.silver.devops.gov.bc.ca
  baseService: strdss-dev

frontend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-dev-frontend
  fullnameOverride: strdss-dev-frontend
  secretName: strdss-secrets-dev

  resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 50Mi

  env:
    'API_HOST': '/api'

backend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-dev-backend
  fullnameOverride: strdss-dev-backend
  secretName: strdss-secrets-dev

  # resources:
  #   limits:
  #     cpu: 1500m
  #     memory: 1500Mi
  #   requests:
  #     cpu: 20m
  #     memory: 1100Mi

  resources:
    limits:
      cpu: 500m
      memory: 300Mi
    requests:
      cpu: 20m
      memory: 200Mi

  env:
    'API_HOST': '/api'
