global:
  env:
    'Logging__LogLevel__Default': 'Information'
    'Logging__LogLevel__Microsoft.EntityFrameworkCore': 'Warning'
    'Logging__LogLevel__Microsoft.AspNetCore': 'Warning'
    'Logging__LogLevel__StrDss.Common.StrDssLogger': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Development'
    'ENV_NAME': 'dev'
    'APP_BASE_URL': 'https://dev.strdata.gov.bc.ca'
    'SSO_CLIENT': 'str-dss-5303'
    'SSO_HOST': 'https://dev.loginproxy.gov.bc.ca/auth'
    'SSO_REALM': 'standard'
    'SSO_AUTHORITY': 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
    'SM_LOGOFF_URL': 'https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi/'
    'CHES_TOKEN_URL': 'https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
    'CHES_URL': 'https://ches-dev.api.gov.bc.ca'
    'RENTAL_LISTING_REPORT_MAX_SIZE': '4'
    'BCEID_URL': 'https://gws1.development.bceid.ca/webservices/client/v10/bceidservice.asmx'
    'BCEID_CACHE_LIFESPAN': '600'
nameOverride: strdss-dev
fullnameOverride: strdss-dev

route:
  host: dev-strdata.apps.silver.devops.gov.bc.ca
  baseService: strdss-dev

frontend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-dev-frontend
  fullnameOverride: strdss-dev-frontend
  secretName: strdss-secrets-dev
  crunchdb: false

  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 50Mi

  env:
    'API_HOST': '/api'

backend:
  enabled: true
  replicaCount: 1
  nameOverride: strdss-dev-backend
  fullnameOverride: strdss-dev-backend
  secretName: strdss-secrets-dev
  dbSecretName: strdssdev-pguser-strdssdev
  crunchydb: false

  # resources:
  #   limits:
  #     cpu: 1500m
  #     memory: 1500Mi
  #   requests:
  #     cpu: 20m
  #     memory: 1100Mi

  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 20m
      memory: 200Mi

  env:
    'API_HOST': '/api'
