load_module /usr/share/nginx/modules/ngx_http_headers_more_filter_module.so;

# See https://hub.docker.com/_/nginx `Running nginx as a non-root user`
worker_processes  auto;

pid        /tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    sendfile           on;
    keepalive_timeout  65;

    more_clear_headers Server;
    proxy_hide_header X-Powered-By;

    server {
        listen       3001;
        server_name  localhost;

        set $cspNonce $request_id;

        access_log  /var/log/nginx/access.log  main;
        # access_log   off;
        error_log   /dev/null;

        # See http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
        server_tokens off;
        # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow
        # add_header Allow "GET, HEAD" always;
        if ( $request_method !~ ^(GET|HEAD)$ ) {
        	return 405;
        }

        include /nginx/nginx.conf;

        location ~* \.(js|css|woff2?)$ {
            limit_except GET POST {
              deny all;
            }

            include /etc/nginx/nginx-security-headers.inc;
            root /nginx/html;
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable" always;
        }

        location / {
            limit_except GET POST {
              deny all;
            }

            include /etc/nginx/nginx-security-headers.inc;
            add_header Cache-Control "no-cache, no-store, must-revalidate" always;
            add_header Pragma "no-cache" always;
            add_header Expires "0" always;

            root /nginx/html;
            index index.html index.htm;

            sub_filter '</head>' '<meta name="csp-nonce" content="$cspNonce"></head>';
            sub_filter_once on;

            try_files $uri $uri.html $uri/index.html /index.html;
        }

        location /api/ {
          include /etc/nginx/nginx-security-headers.inc;

          proxy_pass http://server:8080;
          proxy_http_version 1.1;

          proxy_set_header HOST $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
