version: '2.1'

# https://docs.docker.com/compose/environment-variables/set-environment-variables/#compose-file

volumes:
  db-data:

services:
  strdss-db:
    image: postgis/postgis:16-3.4
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - "5432:5432"

  server:
    build: ./server
    env_file:
      ./docker.env
    ports:
      - "5000:80"
    depends_on:
      strdss-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    env_file:
      ./docker.env
    ports:
      - "5002:3001"
    depends_on:
      - server
