name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  - uses: actions/cache@v4
    with:
      path: |
        **/node_modules
      key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.lock') }}

  - name: Install Root NPM packages
    run: npm install
    shell: bash

  - name: Install Frontend NPM packages
    run: npm install
    working-directory: ./frontend
    shell: bash
