name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Root NPM packages
      run: npm install
      shell: bash

    - name: Install Frontend NPM packages
      run: npm install
      working-directory: ./frontend
      shell: bash
