global:
  labels:
    environment: dev
    env: development
    owner: "b0471a-team"
    project: "b0471a-project"
    DataClass: "Medium"

nameOverride: strdssdev-backup
fullnameOverride: strdssdev-backup

dbService: strdssdev

backupConfig: |
  postgres=strdssdev:5432/strdssdev

  0 1 * * * default ./backup.sh -s

db:
  secretName: strdssdev
  passwordKey: postgres-password

persistence:
  backup:
    size: 1Gi
    mountPath: /backups/
    storageClassName: netapp-file-backup
    storageAccessMode: ReadWriteOnce

env:
  DATABASE_SERVICE_NAME:
    value: strdssdev
  ENVIRONMENT_FRIENDLY_NAME:
    value: "STRDSS DEV DB Backups"
  ENVIRONMENT_NAME:
    value: "dev"
backup-storage:
  labels:
    DataClass: "Medium"
