crunchy-postgres:
  fullnameOverride: strdssprod
  instances:
    name: ha # high availability
    replicas: 2
    dataVolumeClaimSpec:
      storage: 25Gi
      storageClassName: netapp-block-standard
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 768Mi
    replicaCertCopy:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi

  pgBackRest:
    retention: "10" # Ideally a larger number such as 30 backups/days
    # If retention-full-type set to 'count' then the oldest backups will expire when the number of backups reach the number defined in retention
    # If retention-full-type set to 'time' then the number defined in retention will take that many days worth of full backups before expiration
    retentionFullType: time
    repos:
      schedules:
        full: 0 10 * * *
      volume:
        accessModes: "ReadWriteOnce"
        storage: 10Gi
crunchy-postgres-tools:
  networking:
    route:
      host: prod-strdata-db.apps.silver.devops.gov.bc.ca