name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@8b8467c5522bb0aea4977082037e4f2956d67e52

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache tools
      uses: actions/cache@v3
      with:
        path: /home/runner/.asdf
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install required tools
      run: |
        cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
        asdf plugin-add docker-compose https://github.com/virtualstaticvoid/asdf-docker-compose.git || true
        asdf plugin-update --all
        asdf install
        asdf reshim
      shell: bash

    # - name: Install python tools
    #   run: |
    #     pip install -r requirements.txt
    #     asdf reshim
    #   shell: bash
