export const environment = {
    SSO_CLIENT: 'str-dss-5303',
    SSO_REALM: 'standard',
    SSO_HOST: '__SSO_HOST__',
    ENV_NAME: '__ENV_NAME__',
    VERSION: '0.1',
    SM_LOGOFF_URL: '__SM_LOGOFF_URL__',
    API_HOST: '/api',
    RENTAL_LISTING_REPORT_MAX_SIZE: '__RENTAL_LISTING_REPORT_MAX_SIZE__',
    BUISINESS_LICENSE_MAX_SIZE: '__BUISINESS_LICENSE_MAX_SIZE__',
    ADDRESS_SCORE: '__ADDRESS_SCORE__',
};
