/* STR DSS Sprint 6 PROD ONLY Data Seeding */

delete from dss_organization where organization_cd in ('LGNILTA-Denman','LGNILTA-Executive','LGNILTA-Gabriola','LGNILTA-Galiano','LGNILTA-Gambier','LGNILTA-Hornby','LGNILTA-Lasqueti','LGNILTA-Mayne','LGNILTA-North-Pender','LGNILTA-Saturna','LGNILTA-South-Pender','LGNILTA-Thetis');

UPDATE dss_organization set organization_cd='LGMD-Tofino' where organization_cd='LGMV-Tofino';

MERGE INTO dss_organization AS tgt
USING ( SELECT * FROM (VALUES
('LG','LGMC-Abbotsford'          ,'City of Abbotsford'                                   ),
('LG','LGMC-Armstrong'           ,'City of Armstrong'                                    ),
('LG','LGMC-Burnaby'             ,'City of Burnaby'                                      ),
('LG','LGMC-Campbell-River'      ,'City of Campbell River'                               ),
('LG','LGMC-Castlegar'           ,'City of Castlegar'                                    ),
('LG','LGMC-Chilliwack'          ,'City of Chilliwack'                                   ),
('LG','LGMC-Colwood'             ,'City of Colwood'                                      ),
('LG','LGMC-Coquitlam'           ,'City of Coquitlam'                                    ),
('LG','LGMC-Courtenay'           ,'City of Courtenay'                                    ),
('LG','LGMC-Cranbrook'           ,'City of Cranbrook'                                    ),
('LG','LGMC-Dawson-Creek'        ,'City of Dawson Creek'                                 ),
('LG','LGMC-Delta'               ,'City of Delta'                                        ),
('LG','LGMC-Duncan'              ,'City of Duncan'                                       ),
('LG','LGMC-Enderby'             ,'City of Enderby'                                      ),
('LG','LGMC-Fernie'              ,'City of Fernie'                                       ),
('LG','LGMC-Fort-St-John'        ,'City of Fort St John'                                 ),
('LG','LGMC-Grand Forks'         ,'City of Grand Forks'                                  ),
('LG','LGMC-Greenwood'           ,'City of Greenwood'                                    ),
('LG','LGMC-Kamloops'            ,'City of Kamloops'                                     ),
('LG','LGMC-Kelowna'             ,'City of Kelowna'                                      ),
('LG','LGMC-Kimberley'           ,'City of Kimberley'                                    ),
('LG','LGMC-Langford'            ,'City of Langford'                                     ),
('LG','LGMC-Langley'             ,'City of Langley'                                      ),
('LG','LGMC-Maple-Ridge'         ,'City of Maple Ridge'                                  ),
('LG','LGMC-Merritt'             ,'City of Merritt'                                      ),
('LG','LGMC-Mission'             ,'City of Mission'                                      ),
('LG','LGMC-Nanaimo'             ,'City of Nanaimo'                                      ),
('LG','LGMC-Nelson'              ,'City of Nelson'                                       ),
('LG','LGMC-New-Westminster'     ,'City of New Westminster'                              ),
('LG','LGMC-North-Vancouver'     ,'City of North Vancouver'                              ),
('LG','LGMC-Parksville'          ,'City of Parksville'                                   ),
('LG','LGMC-Penticton'           ,'City of Penticton'                                    ),
('LG','LGMC-Pitt-Meadows'        ,'City of Pitt Meadows'                                 ),
('LG','LGMC-Port-Alberni'        ,'City of Port Alberni'                                 ),
('LG','LGMC-Port-Coquitlam'      ,'City of Port Coquitlam'                               ),
('LG','LGMC-Port-Moody'          ,'City of Port Moody'                                   ),
('LG','LGMC-Powell-River'        ,'City of Powell River'                                 ),
('LG','LGMC-Prince-George'       ,'City of Prince George'                                ),
('LG','LGMC-Prince-Rupert'       ,'City of Prince Rupert'                                ),
('LG','LGMC-Quesnel'             ,'City of Quesnel'                                      ),
('LG','LGMC-Revelstoke'          ,'City of Revelstoke'                                   ),
('LG','LGMC-Richmond'            ,'City of Richmond'                                     ),
('LG','LGMC-Rossland'            ,'City of Rossland'                                     ),
('LG','LGMC-Salmon-Arm'          ,'City of Salmon Arm'                                   ),
('LG','LGMC-Surrey'              ,'City of Surrey'                                       ),
('LG','LGMC-Terrace'             ,'City of Terrace'                                      ),
('LG','LGMC-Trail'               ,'City of Trail'                                        ),
('LG','LGMC-Vancouver'           ,'City of Vancouver'                                    ),
('LG','LGMC-Vernon'              ,'City of Vernon'                                       ),
('LG','LGMC-Victoria'            ,'City of Victoria'                                     ),
('LG','LGMC-West-Kelowna'        ,'City of West Kelowna'                                 ),
('LG','LGMC-White-Rock'          ,'City of White Rock'                                   ),
('LG','LGMC-Williams-Lake'       ,'City of Williams Lake'                                ),
('LG','LGMD-West-Vancouver'      ,'District Municipality of West Vancouver'              ),
('LG','LGMD-100-Mile-House'      ,'District of 100 Mile House'                           ),
('LG','LGMD-Barriere'            ,'District of Barriere'                                 ),
('LG','LGMD-Central-Saanich'     ,'District of Central Saanich'                          ),
('LG','LGMD-Chetwynd'            ,'District of Chetwynd'                                 ),
('LG','LGMD-Clearwater'          ,'District of Clearwater'                               ),
('LG','LGMD-Coldstream'          ,'District of Coldstream'                               ),
('LG','LGMD-Elkford'             ,'District of Elkford'                                  ),
('LG','LGMD-Fort-St-James'       ,'District of Fort St James'                            ),
('LG','LGMD-Highlands'           ,'District of Highlands'                                ),
('LG','LGMD-Hope'                ,'District of Hope'                                     ),
('LG','LGMD-Houston'             ,'District of Houston'                                  ),
('LG','LGMD-Hudsons-Hope'        ,'District of Hudsons Hope'                             ),
('LG','LGMD-Invermere'           ,'District of Invermere'                                ),
('LG','LGMD-Kent'                ,'District of Kent'                                     ),
('LG','LGMD-Kitimat'             ,'District of Kitimat'                                  ),
('LG','LGMD-Lake-Country'        ,'District of Lake Country'                             ),
('LG','LGMD-Lantzville'          ,'District of Lantzville'                               ),
('LG','LGMD-Lillooet'            ,'District of Lillooet'                                 ),
('LG','LGMD-Logan-Lake'          ,'District of Logan Lake'                               ),
('LG','LGMD-Mackenzie'           ,'District of Mackenzie'                                ),
('LG','LGMD-Metchosin'           ,'District of Metchosin'                                ),
('LG','LGMD-New-Hazelton'        ,'District of New Hazelton'                             ),
('LG','LGMD-North-Cowichan'      ,'District of North Cowichan'                           ),
('LG','LGMD-North-Saanich'       ,'District of North Saanich'                            ),
('LG','LGMD-North-Vancouver'     ,'District of North Vancouver'                          ),
('LG','LGMD-Oak-Bay'             ,'District of Oak Bay'                                  ),
('LG','LGMD-Peachland'           ,'District of Peachland'                                ),
('LG','LGMD-Port-Edward'         ,'District of Port Edward'                              ),
('LG','LGMD-Port-Hardy'          ,'District of Port Hardy'                               ),
('LG','LGMD-Saanich'             ,'District of Saanich'                                  ),
('LG','LGMD-Sechelt'             ,'District of Sechelt'                                  ),
('LG','LGMD-Sicamous'            ,'District of Sicamous'                                 ),
('LG','LGMD-Sooke'               ,'District of Sooke'                                    ),
('LG','LGMD-Sparwood'            ,'District of Sparwood'                                 ),
('LG','LGMD-Squamish'            ,'District of Squamish'                                 ),
('LG','LGMD-Stewart'             ,'District of Stewart'                                  ),
('LG','LGMD-Summerland'          ,'District of Summerland'                               ),
('LG','LGMD-Taylor'              ,'District of Taylor'                                   ),
('LG','LGMD-Tofino'              ,'District of Tofino'                                   ),
('LG','LGMD-Tumbler-Ridge'       ,'District of Tumbler Ridge'                            ),
('LG','LGMD-Ucluelet'            ,'District of Ucluelet'                                 ),
('LG','LGMD-Vanderhoof'          ,'District of Vanderhoof'                               ),
('LG','LGMD-Wells'               ,'District of Wells'                                    ),
('LG','LGMI-Bowen'               ,'Bowen Island Municipality'                            ),
('LG','LGMR-Northern-Rockies'    ,'Northern Rockies Regional Municipality'               ),
('LG','LGMR-Sun-Peaks-Mountain'  ,'Sun Peaks Mountain Resort Municipality'               ),
('LG','LGMR-Whistler'            ,'Resort Municipality of Whistler'                      ),
('LG','LGMT-Comox'               ,'Town of Comox'                                        ),
('LG','LGMT-Creston'             ,'Town of Creston'                                      ),
('LG','LGMT-Esquimalt'           ,'Township of Esquimalt'                                ),
('LG','LGMT-Gibsons'             ,'Town of Gibsons'                                      ),
('LG','LGMT-Golden'              ,'Town of Golden'                                       ),
('LG','LGMT-Ladysmith'           ,'Town of Ladysmith'                                    ),
('LG','LGMT-Lake-Cowichan'       ,'Town of Lake Cowichan'                                ),
('LG','LGMT-Langley'             ,'Township of Langley'                                  ),
('LG','LGMT-Oliver'              ,'Town of Oliver'                                       ),
('LG','LGMT-Osoyoos'             ,'Town of Osoyoos'                                      ),
('LG','LGMT-Port McNeill'        ,'Town of Port McNeill'                                 ),
('LG','LGMT-Princeton'           ,'Town of Princeton'                                    ),
('LG','LGMT-Qualicum Beach'      ,'Town of Qualicum Beach'                               ),
('LG','LGMT-Sidney'              ,'Town of Sidney'                                       ),
('LG','LGMT-Smithers'            ,'Town of Smithers'                                     ),
('LG','LGMT-Spallumcheen'        ,'Township of Spallumcheen'                             ),
('LG','LGMT-View-Royal'          ,'Town of View Royal'                                   ),
('LG','LGMV-Alert-Bay'           ,'Village of Alert Bay'                                 ),
('LG','LGMV-Anmore'              ,'Village of Anmore'                                    ),
('LG','LGMV-Ashcroft'            ,'Village of Ashcroft'                                  ),
('LG','LGMV-Belcarra'            ,'Village of Belcarra'                                  ),
('LG','LGMV-Burns-Lake'          ,'Village of Burns Lake'                                ),
('LG','LGMV-Cache-Creek'         ,'Village of Cache Creek'                               ),
('LG','LGMV-Canal-Flats'         ,'Village of Canal Flats'                               ),
('LG','LGMV-Chase'               ,'Village of Chase'                                     ),
('LG','LGMV-Clinton'             ,'Village of Clinton'                                   ),
('LG','LGMV-Cumberland'          ,'Village of Cumberland'                                ),
('LG','LGMV-Daajing-Giids'       ,'Village of Daajing Giids'                             ),
('LG','LGMV-Fraser-Lake'         ,'Village of Fraser Lake'                               ),
('LG','LGMV-Fruitvale'           ,'Village of Fruitvale'                                 ),
('LG','LGMV-Gold-River'          ,'Village of Gold River'                                ),
('LG','LGMV-Granisle'            ,'Village of Granisle'                                  ),
('LG','LGMV-Harrison-Hot-Springs','Village of Harrison Hot Springs'                      ),
('LG','LGMV-Hazelton'            ,'Village of Hazelton'                                  ),
('LG','LGMV-Kaslo'               ,'Village of Kaslo'                                     ),
('LG','LGMV-Keremeos'            ,'Village of Keremeos'                                  ),
('LG','LGMV-Lions-Bay'           ,'Village of Lions Bay'                                 ),
('LG','LGMV-Lumby'               ,'Village of Lumby'                                     ),
('LG','LGMV-Lytton'              ,'Village of Lytton'                                    ),
('LG','LGMV-Masset'              ,'Village of Masset'                                    ),
('LG','LGMV-McBride'             ,'Village of McBride'                                   ),
('LG','LGMV-Midway'              ,'Village of Midway'                                    ),
('LG','LGMV-Montrose'            ,'Village of Montrose'                                  ),
('LG','LGMV-Nakusp'              ,'Village of Nakusp'                                    ),
('LG','LGMV-New-Denver'          ,'Village of New Denver'                                ),
('LG','LGMV-Pemberton'           ,'Village of Pemberton'                                 ),
('LG','LGMV-Port-Alice'          ,'Village of Port Alice'                                ),
('LG','LGMV-Port-Clements'       ,'Village of Port Clements'                             ),
('LG','LGMV-Pouce-Coupe'         ,'Village of Pouce Coupe'                               ),
('LG','LGMV-Radium-Hot-Springs'  ,'Village of Radium Hot Springs'                        ),
('LG','LGMV-Salmo'               ,'Village of Salmo'                                     ),
('LG','LGMV-Sayward'             ,'Village of Sayward'                                   ),
('LG','LGMV-Silverton'           ,'Village of Silverton'                                 ),
('LG','LGMV-Slocan'              ,'Village of Slocan'                                    ),
('LG','LGMV-Tahsis'              ,'Village of Tahsis'                                    ),
('LG','LGMV-Telkwa'              ,'Village of Telkwa'                                    ),
('LG','LGMV-Valemount'           ,'Village of Valemount'                                 ),
('LG','LGMV-Warfield'            ,'Village of Warfield'                                  ),
('LG','LGMV-Zeballos'            ,'Village of Zeballos'                                  ),
('LG','LGNILTA-Islands'          ,'Islands Trust'                                        ),
('LG','LGNILTA-Salt-Spring'      ,'Salt Spring Island Local Trust Area'                  ),
('LG','LGPBC-BC-Parks'           ,'BC Parks'                                             ),
('LG','LGRD-Alberni-Clayoquot'   ,'Regional District of Alberni-Clayoquot'               ),
('LG','LGRD-Atlin'               ,'Atlin Community Improvement District'                 ),
('LG','LGRD-Bulkley-Nechako'     ,'Regional District of Bulkley-Nechako'                 ),
('LG','LGRD-Capital'             ,'Capital Regional District'                            ),
('LG','LGRD-Cariboo'             ,'Cariboo Regional District'                            ),
('LG','LGRD-Central-Coast'       ,'Central Coast Regional District'                      ),
('LG','LGRD-Central-Kootenay'    ,'Regional District of Central Kootenay'                ),
('LG','LGRD-Central-Okanagan'    ,'Regional District of Central Okanagan'                ),
('LG','LGRD-Columbia-Shuswap'    ,'Columbia Shuswap Regional District'                   ),
('LG','LGRD-Comox-Valley'        ,'Comox Valley Regional District'                       ),
('LG','LGRD-Cowichan-Valley'     ,'Cowichan Valley Regional District'                    ),
('LG','LGRD-East-Kootenay'       ,'Regional District of East Kootenay'                   ),
('LG','LGRD-Fraser-Fort George'  ,'Regional District of Fraser-Fort George'              ),
('LG','LGRD-Fraser-Valley'       ,'Fraser Valley Regional District'                      ),
('LG','LGRD-Kitimat-Stikine'     ,'Regional District of Kitimat-Stikine'                 ),
('LG','LGRD-Kootenay-Boundary'   ,'Regional District of Kootenay Boundary'               ),
('LG','LGRD-Metro-Vancouver'     ,'Metro Vancouver Regional District'                    ),
('LG','LGRD-Mount-Waddington'    ,'Regional District of Mount Waddington'                ),
('LG','LGRD-Nanaimo'             ,'Regional District of Nanaimo'                         ),
('LG','LGRD-North-Coast'         ,'North Coast Regional District'                        ),
('LG','LGRD-North-Okanagan'      ,'Regional District of North Okanagan'                  ),
('LG','LGRD-Okanagan-Similkameen','Regional District of Okanagan-Similkameen'            ),
('LG','LGRD-Peace-River'         ,'Peace River Regional District'                        ),
('LG','LGRD-qathet'              ,'qathet Regional District'                             ),
('LG','LGRD-Squamish-Lillooet'   ,'Squamish-Lillooet Regional District'                  ),
('LG','LGRD-Strathcona'          ,'Strathcona Regional District'                         ),
('LG','LGRD-Sunshine-Coast'      ,'Sunshine Coast Regional District'                     ),
('LG','LGRD-Thompson-Nicola'     ,'Thompson-Nicola Regional District'                    ),
('LG','LGXFN-Adams-Lake'         ,'Adams Lake Indian Band'                               ),
('LG','LGXFN-Ahousaht'           ,'Ahousaht First Nation'                                ),
('LG','LGXFN-Aitchelitz'         ,'Aitchelitz Band'                                      ),
('LG','LGXFN-?Akisq-nuk'         ,'?Akisq''nuk First Nation'                             ),
('LG','LGXFN-?aqam'              ,'?aqam'                                                ),
('LG','LGXFN-Ashcroft'           ,'Ashcroft Indian Band'                                 ),
('LG','LGXFN-Binche-Whut-en'     ,'Binche Whut''en First Nation'                         ),
('LG','LGXFN-Blueberry-River'    ,'Blueberry River First Nation'                         ),
('LG','LGXFN-Bonaparte'          ,'Bonaparte First Nation'                               ),
('LG','LGXFN-Boothroyd'          ,'Boothroyd Indian Band'                                ),
('LG','LGXFN-Boston Bar'         ,'Boston Bar First Nation'                              ),
('LG','LGXFN-Canim-Lake'         ,'Canim Lake Indian Band (Tsq''escen’)'                 ),
('LG','LGXFN-Cayoose-Creek'      ,'Cayoose Creek Band (Sekw''el''was)'                   ),
('LG','LGXFN-Chawathil'          ,'Chawathil Band'                                       ),
('LG','LGXFN-Cheam'              ,'Cheam First Nation'                                   ),
('LG','LGXFN-Cheslatta'          ,'Cheslatta Indian Band'                                ),
('LG','LGXFN-Coldwater'          ,'Coldwater Indian Band'                                ),
('LG','LGXFN-Cooks-Ferry'        ,'Cook''s Ferry Indian Band'                            ),
('LG','LGXFN-Cowichan'           ,'Cowichan Tribes'                                      ),
('LG','LGXFN-Da-naxda-xw'        ,'Da''naxda''xw First Nation'                           ),
('LG','LGXFN-Dease-River'        ,'Dease River Band Council'                             ),
('LG','LGXFN-Ditidaht'           ,'Ditidaht First Nation'                                ),
('LG','LGXFN-Doig River'         ,'Doig River First Nation'                              ),
('LG','LGXFN-Douglas'            ,'Douglas First Nation (Xa’xtsa)'                       ),
('LG','LGXFN-Dzawada-enuxw'      ,'Dzawada''enuxw First Nation'                          ),
('LG','LGXFN-Ehattesaht'         ,'Ehattesaht First Nation'                              ),
('LG','LGXFN-?Esdilagh'          ,'?Esdilagh First Nation'                               ),
('LG','LGXFN-Esk-etemc'          ,'Esk''etemc First Nation'                              ),
('LG','LGXFN-Fort-Nelson'        ,'Fort Nelson First Nation'                             ),
('LG','LGXFN-Gitanmaax'          ,'Gitanmaax Band Council'                               ),
('LG','LGXFN-Gitanyow'           ,'Gitanyow Hereditary Chiefs'                           ),
('LG','LGXFN-Gitga-at'           ,'Gitga''at First Nation'                               ),
('LG','LGXFN-Gitsegukla'         ,'Gitsegukla Indian Band (Kitsegugkla)'                 ),
('LG','LGXFN-Gitwangak'          ,'Gitwangak Band Council (Kitwanga)'                    ),
('LG','LGXFN-Gitxaala'           ,'Gitxaala Nation (Kitkatla)'                           ),
('LG','LGXFN-Glen-Vowell'        ,'Glen Vowell Indian Band (Sik-e-Dakh)'                 ),
('LG','LGXFN-Gwa-sala-Nakwaxdaxw','Gwa''sala-''Nakwaxda''xw Nation'                      ),
('LG','LGXFN-Gwawaenuk'          ,'Gwawaenuk Tribe'                                      ),
('LG','LGXFN-Hagwilget'          ,'Hagwilget Village Council'                            ),
('LG','LGXFN-Haisla'             ,'Haisla Nation'                                        ),
('LG','LGXFN-Halalt'             ,'Halalt First Nation'                                  ),
('LG','LGXFN-Halfway-River'      ,'Halfway River First Nations'                          ),
('LG','LGXFN-Heiltsuk'           ,'Heiltsuk Nation'                                      ),
('LG','LGXFN-Hesquiaht'          ,'Hesquiaht First Nation'                               ),
('LG','LGXFN-High-Bar'           ,'High Bar First Nation'                                ),
('LG','LGXFN-Homalco '           ,'Homalco (Xwemalhkwu) Indian Band'                     ),
('LG','LGXFN-Hupa-asath'         ,'Hupa¢asath First Nation'                              ),
('LG','LGXFN-Iskut'              ,'Iskut First Nation'                                   ),
('LG','LGXFN-Kanaka'             ,'Kanaka Bar Indian Band'                               ),
('LG','LGXFN-Katzie'             ,'Katzie First Nation'                                  ),
('LG','LGXFN-Kispiox'            ,'Kispiox Band Council'                                 ),
('LG','LGXFN-Kitasoo-Xai-xais'   ,'Kitasoo/Xai''xais Band Council (Klemtu)'              ),
('LG','LGXFN-Kitselas'           ,'Kitselas First Nation'                                ),
('LG','LGXFN-Kitsumkalum'        ,'Kitsumkalum First Nation'                             ),
('LG','LGXFN-Klahoose'           ,'Klahoose First Nation'                                ),
('LG','LGXFN-K-omoks'            ,'K’ómoks First Nation'                                 ),
('LG','LGXFN-Kwadacha'           ,'Kwadacha Nation'                                      ),
('LG','LGXFN-Kwakiutl'           ,'Kwakiutl Indian Band'                                 ),
('LG','LGXFN-Kwantlen'           ,'Kwantlen First Nation'                                ),
('LG','LGXFN-Kwaw-kwaw-Apilt'    ,'Kwaw-kwaw-Apilt First Nation'                         ),
('LG','LGXFN-Kwikwasut-inuxw-Hax','Kwikwasut''inuxw Haxwa''mis First Nation'             ),
('LG','LGXFN-Kwikwetlem'         ,'Kwikwetlem First Nation'                              ),
('LG','LGXFN-Lake-Babine'        ,'Lake Babine Nation'                                   ),
('LG','LGXFN-Lax-Kw-alaams'      ,'Lax Kw''alaams Indian Band'                           ),
('LG','LGXFN-Leq-a-mel'          ,'Leq''a:mel First Nation (Lakahahmen)'                 ),
('LG','LGXFN-Lheidli-T-enneh'    ,'Lheidli T''enneh First Nation'                        ),
('LG','LGXFN-Lhoosk-uz-Dene'     ,'Lhoosk''uz Dene'' Government Administration (Kluskus)'),
('LG','LGXFN-Lhtako-Dene'        ,'Lhtako Dene Nation'                                   ),
('LG','LGXFN-Liard'              ,'Liard First Nation'                                   ),
('LG','LGXFN-Lil-wat'            ,'Lil''wat Nation'                                      ),
('LG','LGXFN-Lower-Kootenay'     ,'Lower Kootenay Indian Band (Yaqan nu?kiy)'            ),
('LG','LGXFN-Lower-Nicola'       ,'Lower Nicola Indian Band'                             ),
('LG','LGXFN-Lower-Similkameen'  ,'Lower Similkameen Indian Band'                        ),
('LG','LGXFN-Lyackson'           ,'Lyackson First Nation'                                ),
('LG','LGXFN-Lytton'             ,'Lytton First Nation'                                  ),
('LG','LGXFN-Malahat'            ,'Malahat First Nation'                                 ),
('LG','LGXFN-Matsqui'            ,'Matsqui First Nation'                                 ),
('LG','LGXFN-McLeod-Lake'        ,'McLeod Lake Indian Band'                              ),
('LG','LGXFN-Metlakatla'         ,'Metlakatla First Nation'                              ),
('LG','LGXFN-Mount-Currie'       ,'Mount Currie Indian Band (Lil''wat)'                  ), -- distinct from Lil'wat Nation?
('LG','LGXFN-Mowachaht-Muchalaht','Mowachaht/Muchalaht First Nation'                     ),
('LG','LGXFN-Musqueam'           ,'Musqueam Indian Band'                                 ),
('LG','LGXFN-Nadleh-Whuten'      ,'Nadleh Whuten Band'                                   ),
('LG','LGXFN-Nak-azdli-Whut-en'  ,'Nak''azdli Whut''en'                                  ),
('LG','LGXFN-Namgis'             ,'‘Namgis First Nation'                                 ),
('LG','LGXFN-Nanoose'            ,'Nanoose First Nation (Snaw-naw-as)'                   ),
('LG','LGXFN-Nazko'              ,'Nazko First Nation'                                   ),
('LG','LGXFN-Nee-Tahi-Buhn'      ,'Nee-Tahi-Buhn Band'                                   ),
('LG','LGXFN-Neskonlith'         ,'Neskonlith Indian Band'                               ),
('LG','LGXFN-Nisga-a'            ,'Nisga''a Nation'                                      ),
('LG','LGXFN-Nooaitch'           ,'Nooaitch Indian Band'                                 ),
('LG','LGXFN-N-Quatqua'          ,'N''Quatqua First Nation'                              ),
('LG','LGXFN-Nuchatlaht'         ,'Nuchatlaht First Nation'                              ),
('LG','LGXFN-Nuxalk'             ,'Nuxalk Nation'                                        ),
('LG','LGXFN-Okanagan'           ,'Okanagan Indian Band'                                 ),
('LG','LGXFN-Old-Massett'        ,'Old Massett Village Council'                          ),
('LG','LGXFN-Oregon-Jack-Creek'  ,'Oregon Jack Creek Band'                               ),
('LG','LGXFN-Osoyoos'            ,'Osoyoos Indian Band'                                  ),
('LG','LGXFN-Pacheedaht'         ,'Pacheedaht First Nation'                              ),
('LG','LGXFN-Pauquachin'         ,'Pauquachin First Nation'                              ),
('LG','LGXFN-Penelakut'          ,'Penelakut Tribe'                                      ),
('LG','LGXFN-Penticton'          ,'Penticton Indian Band'                                ),
('LG','LGXFN-Peters'             ,'Peters Band'                                          ),
('LG','LGXFN-Popkum'             ,'Popkum Indian Band'                                   ),
('LG','LGXFN-Prophet-River'      ,'Prophet River First Nation'                           ),
('LG','LGXFN-Qualicum'           ,'Qualicum First Nation'                                ),
('LG','LGXFN-Quatsino'           ,'Quatsino First Nation'                                ),
('LG','LGXFN-Saik-uz'            ,'Saik''uz First Nation'                                ),
('LG','LGXFN-Samahquam'          ,'Samahquam First Nation'                               ),
('LG','LGXFN-Saulteau'           ,'Saulteau First Nations'                               ),
('LG','LGXFN-Sc-ianew'           ,'Sc''ianew First Nation'                               ),
('LG','LGXFN-Semiahmoo'          ,'Semiahmoo First Nation'                               ),
('LG','LGXFN-Shackan'            ,'Shackan Indian Band'                                  ),
('LG','LGXFN-shishalh'           ,'shíshálh Nation'                                      ),
('LG','LGXFN-Shuswap'            ,'Shuswap Band'                                         ),
('LG','LGXFN-Shxwha-y'           ,'Shxwhá:y Village'                                     ),
('LG','LGXFN-Shxw-ow-hamel'      ,'Shxw''ow''hamel First Nation'                         ),
('LG','LGXFN-Simpcw'             ,'Simpcw First Nation'                                  ),
('LG','LGXFN-Siska'              ,'Siska Indian Band'                                    ),
('LG','LGXFN-Skatin'             ,'Skatin Nations (Skookumchuck)'                        ),
('LG','LGXFN-Skawahlook-Sqewalxw','Skawahlook / Sq’ewá:lxw First Nation'                 ),
('LG','LGXFN-Skeetchestn'        ,'Skeetchestn Indian Band'                              ),
('LG','LGXFN-Skidegate'          ,'Skidegate Band Council'                               ),
('LG','LGXFN-Skin-Tyee'          ,'Skin Tyee Band'                                       ),
('LG','LGXFN-Skowkale'           ,'Skowkale First Nation'                                ),
('LG','LGXFN-Skuppah'            ,'Skuppah Indian Band'                                  ),
('LG','LGXFN-Skwah'              ,'Skwah First Nation'                                   ),
('LG','LGXFN-Skwelax-te-Secwepem','Skwelax te Secwepemcelecw'                            ),
('LG','LGXFN-Snuneymuxw'         ,'Snuneymuxw First Nation'                              ),
('LG','LGXFN-Songhees'           ,'Songhees Nation'                                      ),
('LG','LGXFN-Soowahlie'          ,'Soowahlie Indian Band'                                ),
('LG','LGXFN-Splatsin'           ,'Splatsin Band'                                        ),
('LG','LGXFN-Spuzzum'            ,'Spuzzum (Spô’zêm) First Nation'                       ),
('LG','LGXFN-Sq-ewlets'          ,'Sq''éwlets First Nation'                              ),
('LG','LGXFN-Sq-ewqel'           ,'Sq’éwqel (Seabird Island Band)'                       ),
('LG','LGXFN-Squamish'           ,'Squamish Nation'                                      ),
('LG','LGXFN-Squiala'            ,'Squiala First Nation'                                 ),
('LG','LGXFN-Stellat-en'         ,'Stellat''en First Nation'                             ),
('LG','LGXFN-Sts-ailes'          ,'Sts''ailes Nation'                                    ),
('LG','LGXFN-Stswecem-c-Xgat-tem','Stswecem’c Xgat’tem First Nation'                     ),
('LG','LGXFN-Stz-uminus'         ,'Stz''uminus First Nation'                             ),
('LG','LGXFN-Sumas'              ,'Sumas First Nation'                                   ),
('LG','LGXFN-Tahltan'            ,'Tahltan Band'                                         ),
('LG','LGXFN-Takla'              ,'Takla Nation'                                         ),
('LG','LGXFN-Taku-River-Tlingit' ,'Taku River Tlingit First Nation'                      ),
('LG','LGXFN-T-it-q-et'          ,'T''it''q''et'                                         ),
('LG','LGXFN-Tk-emlups-te-Secwep','Tk''emlúps te Secwépemc'                              ),
('LG','LGXFN-Tla-o-qui-aht'      ,'Tla-o-qui-aht First Nation'                           ),
('LG','LGXFN-Tlatlasikwala'      ,'Tlatlasikwala'                                        ),
('LG','LGXFN-Tl-azt-en'          ,'Tl''azt''en Nation'                                   ),
('LG','LGXFN-Tl-etinqox'         ,'Tl''etinqox Government Office'                        ),
('LG','LGXFN-Tl-etinqox-t-in'    ,'Tl''etinqox-t''in Government Office'                  ),
('LG','LGXFN-Tlowitsis'          ,'Tlowitsis Nation'                                     ),
('LG','LGXFN-Tobacco-Plains'     ,'Tobacco Plains Indian Band'                           ),
('LG','LGXFN-Toosey'             ,'Toosey Indian Band (Tl''esqox)'                       ),
('LG','LGXFN-Tsal-alh'           ,'Tsal''alh'                                            ),
('LG','LGXFN-Tsartlip'           ,'Tsartlip First Nation'                                ),
('LG','LGXFN-Tsawout'            ,'Tsawout First Nation'                                 ),
('LG','LGXFN-Tsawwassen'         ,'Tsawwassen First Nation'                              ),
('LG','LGXFN-Tsay-Keh-Dene'      ,'Tsay Keh Dene'                                        ),
('LG','LGXFN-Tseshaht'           ,'Tseshaht First Nation'                                ),
('LG','LGXFN-Tseycum'            ,'Tseycum First Nation'                                 ),
('LG','LGXFN-Tsideldel'          ,'Tŝideldel First Nation'                               ),
('LG','LGXFN-Ts-il-Kaz-Koh'      ,'Ts’il Kaz Koh First Nation'                           ),
('LG','LGXFN-Ts-kw-aylaxw'       ,'Ts''kw''aylaxw First Nation'                          ),
('LG','LGXFN-Tsleil-Waututh'     ,'Tsleil-Waututh Nation'                                ),
('LG','LGXFN-T-sou-ke'           ,'T''sou-ke Nation'                                     ),
('LG','LGXFN-Tsq-escen'          ,'Tsq''escen'' First Nation'                            ),
('LG','LGXFN-Ts-uubaa-asatx'     ,'Ts''uubaa-asatx'                                      ),
('LG','LGXFN-Tzeachten'          ,'Tzeachten First Nation'                               ),
('LG','LGXFN-Ulkatcho'           ,'Ulkatcho First Nation'                                ),
('LG','LGXFN-Union-Bar'          ,'Union Bar Indian Band'                                ),
('LG','LGXFN-Upper-Nicola'       ,'Upper Nicola Band'                                    ),
('LG','LGXFN-Upper-Similkameen'  ,'Upper Similkameen Indian Band'                        ),
('LG','LGXFN-Westbank'           ,'Westbank First Nation'                                ),
('LG','LGXFN-West-Moberly'       ,'West Moberly First Nations'                           ),
('LG','LGXFN-Wet-suwet-en'       ,'Wet''suwet''en First Nation'                          ),
('LG','LGXFN-We-Wai-Kai'         ,'We Wai Kai Nation'                                    ),
('LG','LGXFN-We-Wai-Kum'         ,'We Wai Kum First Nation'                              ),
('LG','LGXFN-Whispering-Pines-Cl','Whispering Pines/Clinton Indian Band'                 ),
('LG','LGXFN-Williams-Lake'      ,'Williams Lake First Nation'                           ),
('LG','LGXFN-Witset'             ,'Witset First Nation'                                  ),
('LG','LGXFN-Wuikinuxv'          ,'Wuikinuxv First Nation'                               ),
('LG','LGXFN-Xat-sull'           ,'Xat''sull First Nation'                               ),
('LG','LGXFN-Xaxli-p'            ,'Xaxli''p First Nation'                                ),
('LG','LGXFN-Xeni-Gwet-in'       ,'Xeni Gwet''in First Nations Government'               ),
('LG','LGXFN-Xwísten'            ,'Xwísten'                                              ),
('LG','LGXFN-Yakweakwioose'      ,'Yakweakwioose First Nation'                           ),
('LG','LGXFN-Yale'               ,'Yale First Nation'                                    ),
('LG','LGXFN-Yekooche'           ,'Yekooche First Nation'                                ),
('LG','LGXFN-Yunesit-in'         ,'Yunesit''in First Nation'                             ),
('Platform','PLAT-Airbnb','Airbnb'),
('Platform','PLAT-Booking','Booking.com'),
('Platform','PLAT-Expedia','Expedia'))
AS s (organization_type, organization_cd, organization_nm)
) AS src
ON (tgt.organization_cd=src.organization_cd)
WHEN matched and (
tgt.organization_nm!=src.organization_nm or
tgt.organization_type!=src.organization_type)
THEN UPDATE SET
organization_nm=src.organization_nm,
organization_type=src.organization_type
WHEN NOT MATCHED
THEN INSERT (organization_type, organization_cd, organization_nm)
VALUES (src.organization_type, src.organization_cd, src.organization_nm);
