/* STR DSS Sprint 6 PROD ONLY Data Seeding */

UPDATE dss_organization set organization_cd='LGMD-Tofino' where organization_cd='LGMV-Tofino';

MERGE INTO dss_organization AS tgt
USING ( SELECT * FROM (VALUES
('LG','LGMC-Abbotsford'          ,'City of Abbotsford'                       ),
('LG','LGMC-Armstrong'           ,'City of Armstrong'                        ),
('LG','LGMC-Burnaby'             ,'City of Burnaby'                          ),
('LG','LGMC-Campbell-River'      ,'City of Campbell River'                   ),
('LG','LGMC-Castlegar'           ,'City of Castlegar'                        ),
('LG','LGMC-Chilliwack'          ,'City of Chilliwack'                       ),
('LG','LGMC-Colwood'             ,'City of Colwood'                          ),
('LG','LGMC-Coquitlam'           ,'City of Coquitlam'                        ),
('LG','LGMC-Courtenay'           ,'City of Courtenay'                        ),
('LG','LGMC-Cranbrook'           ,'City of Cranbrook'                        ),
('LG','LGMC-Dawson-Creek'        ,'City of Dawson Creek'                     ),
('LG','LGMC-Delta'               ,'City of Delta'                            ),
('LG','LGMC-Duncan'              ,'City of Duncan'                           ),
('LG','LGMC-Enderby'             ,'City of Enderby'                          ),
('LG','LGMC-Fernie'              ,'City of Fernie'                           ),
('LG','LGMC-Fort-St-John'        ,'City of Fort St John'                     ),
('LG','LGMC-Grand Forks'         ,'City of Grand Forks'                      ),
('LG','LGMC-Greenwood'           ,'City of Greenwood'                        ),
('LG','LGMC-Kamloops'            ,'City of Kamloops'                         ),
('LG','LGMC-Kelowna'             ,'City of Kelowna'                          ),
('LG','LGMC-Kimberley'           ,'City of Kimberley'                        ),
('LG','LGMC-Langford'            ,'City of Langford'                         ),
('LG','LGMC-Langley'             ,'City of Langley'                          ),
('LG','LGMC-Maple-Ridge'         ,'City of Maple Ridge'                      ),
('LG','LGMC-Merritt'             ,'City of Merritt'                          ),
('LG','LGMC-Mission'             ,'City of Mission'                          ),
('LG','LGMC-Nanaimo'             ,'City of Nanaimo'                          ),
('LG','LGMC-Nelson'              ,'City of Nelson'                           ),
('LG','LGMC-New-Westminster'     ,'City of New Westminster'                  ),
('LG','LGMC-North-Vancouver'     ,'City of North Vancouver'                  ),
('LG','LGMC-Parksville'          ,'City of Parksville'                       ),
('LG','LGMC-Penticton'           ,'City of Penticton'                        ),
('LG','LGMC-Pitt-Meadows'        ,'City of Pitt Meadows'                     ),
('LG','LGMC-Port-Alberni'        ,'City of Port Alberni'                     ),
('LG','LGMC-Port-Coquitlam'      ,'City of Port Coquitlam'                   ),
('LG','LGMC-Port-Moody'          ,'City of Port Moody'                       ),
('LG','LGMC-Powell-River'        ,'City of Powell River'                     ),
('LG','LGMC-Prince-George'       ,'City of Prince George'                    ),
('LG','LGMC-Prince-Rupert'       ,'City of Prince Rupert'                    ),
('LG','LGMC-Quesnel'             ,'City of Quesnel'                          ),
('LG','LGMC-Revelstoke'          ,'City of Revelstoke'                       ),
('LG','LGMC-Richmond'            ,'City of Richmond'                         ),
('LG','LGMC-Rossland'            ,'City of Rossland'                         ),
('LG','LGMC-Salmon-Arm'          ,'City of Salmon Arm'                       ),
('LG','LGMC-Surrey'              ,'City of Surrey'                           ),
('LG','LGMC-Terrace'             ,'City of Terrace'                          ),
('LG','LGMC-Trail'               ,'City of Trail'                            ),
('LG','LGMC-Vancouver'           ,'City of Vancouver'                        ),
('LG','LGMC-Vernon'              ,'City of Vernon'                           ),
('LG','LGMC-Victoria'            ,'City of Victoria'                         ),
('LG','LGMC-West-Kelowna'        ,'City of West Kelowna'                     ),
('LG','LGMC-White-Rock'          ,'City of White Rock'                       ),
('LG','LGMC-Williams-Lake'       ,'City of Williams Lake'                    ),
('LG','LGMD-West-Vancouver'      ,'District Municipality of West Vancouver'  ),
('LG','LGMD-100-Mile-House'      ,'District of 100 Mile House'               ),
('LG','LGMD-Barriere'            ,'District of Barriere'                     ),
('LG','LGMD-Central-Saanich'     ,'District of Central Saanich'              ),
('LG','LGMD-Chetwynd'            ,'District of Chetwynd'                     ),
('LG','LGMD-Clearwater'          ,'District of Clearwater'                   ),
('LG','LGMD-Coldstream'          ,'District of Coldstream'                   ),
('LG','LGMD-Elkford'             ,'District of Elkford'                      ),
('LG','LGMD-Fort-St-James'       ,'District of Fort St James'                ),
('LG','LGMD-Highlands'           ,'District of Highlands'                    ),
('LG','LGMD-Hope'                ,'District of Hope'                         ),
('LG','LGMD-Houston'             ,'District of Houston'                      ),
('LG','LGMD-Hudsons-Hope'        ,'District of Hudsons Hope'                 ),
('LG','LGMD-Invermere'           ,'District of Invermere'                    ),
('LG','LGMD-Kent'                ,'District of Kent'                         ),
('LG','LGMD-Kitimat'             ,'District of Kitimat'                      ),
('LG','LGMD-Lake-Country'        ,'District of Lake Country'                 ),
('LG','LGMD-Lantzville'          ,'District of Lantzville'                   ),
('LG','LGMD-Lillooet'            ,'District of Lillooet'                     ),
('LG','LGMD-Logan-Lake'          ,'District of Logan Lake'                   ),
('LG','LGMD-Mackenzie'           ,'District of Mackenzie'                    ),
('LG','LGMD-Metchosin'           ,'District of Metchosin'                    ),
('LG','LGMD-New-Hazelton'        ,'District of New Hazelton'                 ),
('LG','LGMD-North-Cowichan'      ,'District of North Cowichan'               ),
('LG','LGMD-North-Saanich'       ,'District of North Saanich'                ),
('LG','LGMD-North-Vancouver'     ,'District of North Vancouver'              ),
('LG','LGMD-Oak-Bay'             ,'District of Oak Bay'                      ),
('LG','LGMD-Peachland'           ,'District of Peachland'                    ),
('LG','LGMD-Port-Edward'         ,'District of Port Edward'                  ),
('LG','LGMD-Port-Hardy'          ,'District of Port Hardy'                   ),
('LG','LGMD-Saanich'             ,'District of Saanich'                      ),
('LG','LGMD-Sechelt'             ,'District of Sechelt'                      ),
('LG','LGMD-Sicamous'            ,'District of Sicamous'                     ),
('LG','LGMD-Sooke'               ,'District of Sooke'                        ),
('LG','LGMD-Sparwood'            ,'District of Sparwood'                     ),
('LG','LGMD-Squamish'            ,'District of Squamish'                     ),
('LG','LGMD-Stewart'             ,'District of Stewart'                      ),
('LG','LGMD-Summerland'          ,'District of Summerland'                   ),
('LG','LGMD-Taylor'              ,'District of Taylor'                       ),
('LG','LGMD-Tofino'              ,'District of Tofino'                       ),
('LG','LGMD-Tumbler-Ridge'       ,'District of Tumbler Ridge'                ),
('LG','LGMD-Ucluelet'            ,'District of Ucluelet'                     ),
('LG','LGMD-Vanderhoof'          ,'District of Vanderhoof'                   ),
('LG','LGMD-Wells'               ,'District of Wells'                        ),
('LG','LGMR-Northern-Rockies'    ,'Northern Rockies Regional Municipality'   ),
('LG','LGMR-Sun-Peaks-Mountain'  ,'Sun Peaks Mountain Resort Municipality'   ),
('LG','LGMR-Whistler'            ,'Resort Municipality of Whistler'          ),
('LG','LGMT-Comox'               ,'Town of Comox'                            ),
('LG','LGMT-Creston'             ,'Town of Creston'                          ),
('LG','LGMT-Esquimalt'           ,'Township of Esquimalt'                    ),
('LG','LGMT-Gibsons'             ,'Town of Gibsons'                          ),
('LG','LGMT-Golden'              ,'Town of Golden'                           ),
('LG','LGMT-Ladysmith'           ,'Town of Ladysmith'                        ),
('LG','LGMT-Lake-Cowichan'       ,'Town of Lake Cowichan'                    ),
('LG','LGMT-Langley'             ,'Township of Langley'                      ),
('LG','LGMT-Oliver'              ,'Town of Oliver'                           ),
('LG','LGMT-Osoyoos'             ,'Town of Osoyoos'                          ),
('LG','LGMT-Port McNeill'        ,'Town of Port McNeill'                     ),
('LG','LGMT-Princeton'           ,'Town of Princeton'                        ),
('LG','LGMT-Qualicum Beach'      ,'Town of Qualicum Beach'                   ),
('LG','LGMT-Sidney'              ,'Town of Sidney'                           ),
('LG','LGMT-Smithers'            ,'Town of Smithers'                         ),
('LG','LGMT-Spallumcheen'        ,'Township of Spallumcheen'                 ),
('LG','LGMT-View-Royal'          ,'Town of View Royal'                       ),
('LG','LGMV-Alert-Bay'           ,'Village of Alert Bay'                     ),
('LG','LGMV-Anmore'              ,'Village of Anmore'                        ),
('LG','LGMV-Ashcroft'            ,'Village of Ashcroft'                      ),
('LG','LGMV-Belcarra'            ,'Village of Belcarra'                      ),
('LG','LGMV-Burns-Lake'          ,'Village of Burns Lake'                    ),
('LG','LGMV-Cache-Creek'         ,'Village of Cache Creek'                   ),
('LG','LGMV-Canal-Flats'         ,'Village of Canal Flats'                   ),
('LG','LGMV-Chase'               ,'Village of Chase'                         ),
('LG','LGMV-Clinton'             ,'Village of Clinton'                       ),
('LG','LGMV-Cumberland'          ,'Village of Cumberland'                    ),
('LG','LGMV-Daajing-Giids'       ,'Village of Daajing Giids'                 ),
('LG','LGMV-Fraser-Lake'         ,'Village of Fraser Lake'                   ),
('LG','LGMV-Fruitvale'           ,'Village of Fruitvale'                     ),
('LG','LGMV-Gold-River'          ,'Village of Gold River'                    ),
('LG','LGMV-Granisle'            ,'Village of Granisle'                      ),
('LG','LGMV-Harrison-Hot-Springs','Village of Harrison Hot Springs'          ),
('LG','LGMV-Hazelton'            ,'Village of Hazelton'                      ),
('LG','LGMV-Kaslo'               ,'Village of Kaslo'                         ),
('LG','LGMV-Keremeos'            ,'Village of Keremeos'                      ),
('LG','LGMV-Lions-Bay'           ,'Village of Lions Bay'                     ),
('LG','LGMV-Lumby'               ,'Village of Lumby'                         ),
('LG','LGMV-Lytton'              ,'Village of Lytton'                        ),
('LG','LGMV-Masset'              ,'Village of Masset'                        ),
('LG','LGMV-McBride'             ,'Village of McBride'                       ),
('LG','LGMV-Midway'              ,'Village of Midway'                        ),
('LG','LGMV-Montrose'            ,'Village of Montrose'                      ),
('LG','LGMV-Nakusp'              ,'Village of Nakusp'                        ),
('LG','LGMV-New-Denver'          ,'Village of New Denver'                    ),
('LG','LGMV-Pemberton'           ,'Village of Pemberton'                     ),
('LG','LGMV-Port-Alice'          ,'Village of Port Alice'                    ),
('LG','LGMV-Port-Clements'       ,'Village of Port Clements'                 ),
('LG','LGMV-Pouce-Coupe'         ,'Village of Pouce Coupe'                   ),
('LG','LGMV-Radium-Hot-Springs'  ,'Village of Radium Hot Springs'            ),
('LG','LGMV-Salmo'               ,'Village of Salmo'                         ),
('LG','LGMV-Sayward'             ,'Village of Sayward'                       ),
('LG','LGMV-Silverton'           ,'Village of Silverton'                     ),
('LG','LGMV-Slocan'              ,'Village of Slocan'                        ),
('LG','LGMV-Tahsis'              ,'Village of Tahsis'                        ),
('LG','LGMV-Telkwa'              ,'Village of Telkwa'                        ),
('LG','LGMV-Valemount'           ,'Village of Valemount'                     ),
('LG','LGMV-Warfield'            ,'Village of Warfield'                      ),
('LG','LGMV-Zeballos'            ,'Village of Zeballos'                      ),
('LG','LGNILTA-Denman'           ,'Denman Island Local Trust Area'           ),
('LG','LGNILTA-Executive'        ,'Executive Islands Local Trust Area'       ),
('LG','LGNILTA-Gabriola'         ,'Gabriola Island Local Trust Area'         ),
('LG','LGNILTA-Galiano'          ,'Galiano Island Local Trust Area'          ),
('LG','LGNILTA-Gambier'          ,'Gambier Island Local Trust Area'          ),
('LG','LGNILTA-Hornby'           ,'Hornby Island Local Trust Area'           ),
('LG','LGNILTA-Lasqueti'         ,'Lasqueti Island Local Trust Area'         ),
('LG','LGNILTA-Mayne'            ,'Mayne Island Local Trust Area'            ),
('LG','LGNILTA-North-Pender'     ,'North Pender Island Local Trust Area'     ),
('LG','LGNILTA-Salt-Spring'      ,'Salt Spring Island Local Trust Area'      ),
('LG','LGNILTA-Saturna'          ,'Saturna Island Local Trust Area'          ),
('LG','LGNILTA-South-Pender'     ,'South Pender Island Local Trust Area'     ),
('LG','LGNILTA-Thetis'           ,'Thetis Island Local Trust Area'           ),
('LG','LGRD-Alberni-Clayoquot'   ,'Regional District of Alberni-Clayoquot'   ),
('LG','LGRD-Bulkley-Nechako'     ,'Regional District of Bulkley-Nechako'     ),
('LG','LGRD-Capital'             ,'Capital Regional District'                ),
('LG','LGRD-Cariboo'             ,'Cariboo Regional District'                ),
('LG','LGRD-Central-Coast'       ,'Central Coast Regional District'          ),
('LG','LGRD-Central-Kootenay'    ,'Regional District of Central Kootenay'    ),
('LG','LGRD-Central-Okanagan'    ,'Regional District of Central Okanagan'    ),
('LG','LGRD-Columbia-Shuswap'    ,'Columbia Shuswap Regional District'       ),
('LG','LGRD-Comox-Valley'        ,'Comox Valley Regional District'           ),
('LG','LGRD-Cowichan-Valley'     ,'Cowichan Valley Regional District'        ),
('LG','LGRD-East-Kootenay'       ,'Regional District of East Kootenay'       ),
('LG','LGRD-Fraser-Fort George'  ,'Regional District of Fraser-Fort George'  ),
('LG','LGRD-Fraser-Valley'       ,'Fraser Valley Regional District'          ),
('LG','LGRD-Kitimat-Stikine'     ,'Regional District of Kitimat-Stikine'     ),
('LG','LGRD-Kootenay-Boundary'   ,'Regional District of Kootenay Boundary'   ),
('LG','LGRD-Metro-Vancouver'     ,'Metro Vancouver Regional District'        ),
('LG','LGRD-Mount-Waddington'    ,'Regional District of Mount Waddington'    ),
('LG','LGRD-Nanaimo'             ,'Regional District of Nanaimo'             ),
('LG','LGRD-North-Coast'         ,'North Coast Regional District'            ),
('LG','LGRD-North-Okanagan'      ,'Regional District of North Okanagan'      ),
('LG','LGRD-Okanagan-Similkameen','Regional District of Okanagan-Similkameen'),
('LG','LGRD-Peace-River'         ,'Peace River Regional District'            ),
('LG','LGRD-qathet'              ,'qathet Regional District'                 ),
('LG','LGRD-Squamish-Lillooet'   ,'Squamish-Lillooet Regional District'      ),
('LG','LGRD-Strathcona'          ,'Strathcona Regional District'             ),
('LG','LGRD-Sunshine-Coast'      ,'Sunshine Coast Regional District'         ),
('LG','LGRD-Thompson-Nicola'     ,'Thompson-Nicola Regional District'        ),
('Platform','PLAT-Airbnb','Airbnb'),
('Platform','PLAT-Booking','Booking.com'),
('Platform','PLAT-Expedia','Expedia'))
AS s (organization_type, organization_cd, organization_nm)
) AS src
ON (tgt.organization_cd=src.organization_cd)
WHEN matched and (
tgt.organization_nm!=src.organization_nm or
tgt.organization_type!=src.organization_type)
THEN UPDATE SET
organization_nm=src.organization_nm,
organization_type=src.organization_type
WHEN NOT MATCHED
THEN INSERT (organization_type, organization_cd, organization_nm)
VALUES (src.organization_type, src.organization_cd, src.organization_nm);
