/* STR DSS Sprint 11 Local Governments Data Seeding */

MERGE INTO dss_organization AS tgt
USING ( SELECT * FROM (VALUES
('LG','Municipality'                    ,'LGMC-Abbotsford'          ,'City of Abbotsford'                                   ),
('LG','Municipality'                    ,'LGMC-Armstrong'           ,'City of Armstrong'                                    ),
('LG','Municipality'                    ,'LGMC-Burnaby'             ,'City of Burnaby'                                      ),
('LG','Municipality'                    ,'LGMC-Campbell-River'      ,'City of Campbell River'                               ),
('LG','Municipality'                    ,'LGMC-Castlegar'           ,'City of Castlegar'                                    ),
('LG','Municipality'                    ,'LGMC-Chilliwack'          ,'City of Chilliwack'                                   ),
('LG','Municipality'                    ,'LGMC-Colwood'             ,'City of Colwood'                                      ),
('LG','Municipality'                    ,'LGMC-Coquitlam'           ,'City of Coquitlam'                                    ),
('LG','Municipality'                    ,'LGMC-Courtenay'           ,'City of Courtenay'                                    ),
('LG','Municipality'                    ,'LGMC-Cranbrook'           ,'City of Cranbrook'                                    ),
('LG','Municipality'                    ,'LGMC-Dawson-Creek'        ,'City of Dawson Creek'                                 ),
('LG','Municipality'                    ,'LGMC-Delta'               ,'City of Delta'                                        ),
('LG','Municipality'                    ,'LGMC-Duncan'              ,'City of Duncan'                                       ),
('LG','Municipality'                    ,'LGMC-Enderby'             ,'City of Enderby'                                      ),
('LG','Municipality'                    ,'LGMC-Fernie'              ,'City of Fernie'                                       ),
('LG','Municipality'                    ,'LGMC-Fort-St-John'        ,'City of Fort St John'                                 ),
('LG','Municipality'                    ,'LGMC-Grand-Forks'         ,'City of Grand Forks'                                  ),
('LG','Municipality'                    ,'LGMC-Greenwood'           ,'City of Greenwood'                                    ),
('LG','Municipality'                    ,'LGMC-Kamloops'            ,'City of Kamloops'                                     ),
('LG','Municipality'                    ,'LGMC-Kelowna'             ,'City of Kelowna'                                      ),
('LG','Municipality'                    ,'LGMC-Kimberley'           ,'City of Kimberley'                                    ),
('LG','Municipality'                    ,'LGMC-Langford'            ,'City of Langford'                                     ),
('LG','Municipality'                    ,'LGMC-Langley'             ,'City of Langley'                                      ),
('LG','Municipality'                    ,'LGMC-Maple-Ridge'         ,'City of Maple Ridge'                                  ),
('LG','Municipality'                    ,'LGMC-Merritt'             ,'City of Merritt'                                      ),
('LG','Municipality'                    ,'LGMC-Mission'             ,'City of Mission'                                      ),
('LG','Municipality'                    ,'LGMC-Nanaimo'             ,'City of Nanaimo'                                      ),
('LG','Municipality'                    ,'LGMC-Nelson'              ,'City of Nelson'                                       ),
('LG','Municipality'                    ,'LGMC-New-Westminster'     ,'City of New Westminster'                              ),
('LG','Municipality'                    ,'LGMC-North-Vancouver'     ,'City of North Vancouver'                              ),
('LG','Municipality'                    ,'LGMC-Parksville'          ,'City of Parksville'                                   ),
('LG','Municipality'                    ,'LGMC-Penticton'           ,'City of Penticton'                                    ),
('LG','Municipality'                    ,'LGMC-Pitt-Meadows'        ,'City of Pitt Meadows'                                 ),
('LG','Municipality'                    ,'LGMC-Port-Alberni'        ,'City of Port Alberni'                                 ),
('LG','Municipality'                    ,'LGMC-Port-Coquitlam'      ,'City of Port Coquitlam'                               ),
('LG','Municipality'                    ,'LGMC-Port-Moody'          ,'City of Port Moody'                                   ),
('LG','Municipality'                    ,'LGMC-Powell-River'        ,'City of Powell River'                                 ),
('LG','Municipality'                    ,'LGMC-Prince-George'       ,'City of Prince George'                                ),
('LG','Municipality'                    ,'LGMC-Prince-Rupert'       ,'City of Prince Rupert'                                ),
('LG','Municipality'                    ,'LGMC-Quesnel'             ,'City of Quesnel'                                      ),
('LG','Municipality'                    ,'LGMC-Revelstoke'          ,'City of Revelstoke'                                   ),
('LG','Municipality'                    ,'LGMC-Richmond'            ,'City of Richmond'                                     ),
('LG','Municipality'                    ,'LGMC-Rossland'            ,'City of Rossland'                                     ),
('LG','Municipality'                    ,'LGMC-Salmon-Arm'          ,'City of Salmon Arm'                                   ),
('LG','Municipality'                    ,'LGMC-Surrey'              ,'City of Surrey'                                       ),
('LG','Municipality'                    ,'LGMC-Terrace'             ,'City of Terrace'                                      ),
('LG','Municipality'                    ,'LGMC-Trail'               ,'City of Trail'                                        ),
('LG','Municipality'                    ,'LGMC-Vancouver'           ,'City of Vancouver'                                    ),
('LG','Municipality'                    ,'LGMC-Vernon'              ,'City of Vernon'                                       ),
('LG','Municipality'                    ,'LGMC-Victoria'            ,'City of Victoria'                                     ),
('LG','Municipality'                    ,'LGMC-West-Kelowna'        ,'City of West Kelowna'                                 ),
('LG','Municipality'                    ,'LGMC-White-Rock'          ,'City of White Rock'                                   ),
('LG','Municipality'                    ,'LGMC-Williams-Lake'       ,'City of Williams Lake'                                ),
('LG','Municipality'                    ,'LGMD-West-Vancouver'      ,'District Municipality of West Vancouver'              ),
('LG','Municipality'                    ,'LGMD-100-Mile-House'      ,'District of 100 Mile House'                           ),
('LG','Municipality'                    ,'LGMD-Barriere'            ,'District of Barriere'                                 ),
('LG','Municipality'                    ,'LGMD-Central-Saanich'     ,'District of Central Saanich'                          ),
('LG','Municipality'                    ,'LGMD-Chetwynd'            ,'District of Chetwynd'                                 ),
('LG','Municipality'                    ,'LGMD-Clearwater'          ,'District of Clearwater'                               ),
('LG','Municipality'                    ,'LGMD-Coldstream'          ,'District of Coldstream'                               ),
('LG','Municipality'                    ,'LGMD-Elkford'             ,'District of Elkford'                                  ),
('LG','Municipality'                    ,'LGMD-Fort-St-James'       ,'District of Fort St James'                            ),
('LG','Municipality'                    ,'LGMD-Highlands'           ,'District of Highlands'                                ),
('LG','Municipality'                    ,'LGMD-Hope'                ,'District of Hope'                                     ),
('LG','Municipality'                    ,'LGMD-Houston'             ,'District of Houston'                                  ),
('LG','Municipality'                    ,'LGMD-Hudsons-Hope'        ,'District of Hudsons Hope'                             ),
('LG','Municipality'                    ,'LGMD-Invermere'           ,'District of Invermere'                                ),
('LG','Municipality'                    ,'LGMD-Kent'                ,'District of Kent'                                     ),
('LG','Municipality'                    ,'LGMD-Kitimat'             ,'District of Kitimat'                                  ),
('LG','Municipality'                    ,'LGMD-Lake-Country'        ,'District of Lake Country'                             ),
('LG','Municipality'                    ,'LGMD-Lantzville'          ,'District of Lantzville'                               ),
('LG','Municipality'                    ,'LGMD-Lillooet'            ,'District of Lillooet'                                 ),
('LG','Municipality'                    ,'LGMD-Logan-Lake'          ,'District of Logan Lake'                               ),
('LG','Municipality'                    ,'LGMD-Mackenzie'           ,'District of Mackenzie'                                ),
('LG','Municipality'                    ,'LGMD-Metchosin'           ,'District of Metchosin'                                ),
('LG','Municipality'                    ,'LGMD-New-Hazelton'        ,'District of New Hazelton'                             ),
('LG','Municipality'                    ,'LGMD-North-Cowichan'      ,'District of North Cowichan'                           ),
('LG','Municipality'                    ,'LGMD-North-Saanich'       ,'District of North Saanich'                            ),
('LG','Municipality'                    ,'LGMD-North-Vancouver'     ,'District of North Vancouver'                          ),
('LG','Municipality'                    ,'LGMD-Oak-Bay'             ,'District of Oak Bay'                                  ),
('LG','Municipality'                    ,'LGMD-Peachland'           ,'District of Peachland'                                ),
('LG','Municipality'                    ,'LGMD-Port-Edward'         ,'District of Port Edward'                              ),
('LG','Municipality'                    ,'LGMD-Port-Hardy'          ,'District of Port Hardy'                               ),
('LG','Municipality'                    ,'LGMD-Saanich'             ,'District of Saanich'                                  ),
('LG','Municipality'                    ,'LGMD-Sechelt'             ,'District of Sechelt'                                  ),
('LG','Municipality'                    ,'LGMD-Sicamous'            ,'District of Sicamous'                                 ),
('LG','Municipality'                    ,'LGMD-Sooke'               ,'District of Sooke'                                    ),
('LG','Municipality'                    ,'LGMD-Sparwood'            ,'District of Sparwood'                                 ),
('LG','Municipality'                    ,'LGMD-Squamish'            ,'District of Squamish'                                 ),
('LG','Municipality'                    ,'LGMD-Stewart'             ,'District of Stewart'                                  ),
('LG','Municipality'                    ,'LGMD-Summerland'          ,'District of Summerland'                               ),
('LG','Municipality'                    ,'LGMD-Taylor'              ,'District of Taylor'                                   ),
('LG','Municipality'                    ,'LGMD-Tofino'              ,'District of Tofino'                                   ),
('LG','Municipality'                    ,'LGMD-Tumbler-Ridge'       ,'District of Tumbler Ridge'                            ),
('LG','Municipality'                    ,'LGMD-Ucluelet'            ,'District of Ucluelet'                                 ),
('LG','Municipality'                    ,'LGMD-Vanderhoof'          ,'District of Vanderhoof'                               ),
('LG','Municipality'                    ,'LGMD-Wells'               ,'District of Wells'                                    ),
('LG','Municipality'                    ,'LGMI-Bowen'               ,'Bowen Island Municipality'                            ),
('LG','Municipality'                    ,'LGMR-Northern-Rockies'    ,'Northern Rockies Regional Municipality'               ),
('LG','Municipality'                    ,'LGMR-Sun-Peaks-Mountain'  ,'Sun Peaks Mountain Resort Municipality'               ),
('LG','Municipality'                    ,'LGMR-Whistler'            ,'Resort Municipality of Whistler'                      ),
('LG','Municipality'                    ,'LGMT-Comox'               ,'Town of Comox'                                        ),
('LG','Municipality'                    ,'LGMT-Creston'             ,'Town of Creston'                                      ),
('LG','Municipality'                    ,'LGMT-Esquimalt'           ,'Township of Esquimalt'                                ),
('LG','Municipality'                    ,'LGMT-Gibsons'             ,'Town of Gibsons'                                      ),
('LG','Municipality'                    ,'LGMT-Golden'              ,'Town of Golden'                                       ),
('LG','Municipality'                    ,'LGMT-Ladysmith'           ,'Town of Ladysmith'                                    ),
('LG','Municipality'                    ,'LGMT-Lake-Cowichan'       ,'Town of Lake Cowichan'                                ),
('LG','Municipality'                    ,'LGMT-Langley'             ,'Township of Langley'                                  ),
('LG','Municipality'                    ,'LGMT-Oliver'              ,'Town of Oliver'                                       ),
('LG','Municipality'                    ,'LGMT-Osoyoos'             ,'Town of Osoyoos'                                      ),
('LG','Municipality'                    ,'LGMT-Port-McNeill'        ,'Town of Port McNeill'                                 ),
('LG','Municipality'                    ,'LGMT-Princeton'           ,'Town of Princeton'                                    ),
('LG','Municipality'                    ,'LGMT-Qualicum-Beach'      ,'Town of Qualicum Beach'                               ),
('LG','Municipality'                    ,'LGMT-Sidney'              ,'Town of Sidney'                                       ),
('LG','Municipality'                    ,'LGMT-Smithers'            ,'Town of Smithers'                                     ),
('LG','Municipality'                    ,'LGMT-Spallumcheen'        ,'Township of Spallumcheen'                             ),
('LG','Municipality'                    ,'LGMT-View-Royal'          ,'Town of View Royal'                                   ),
('LG','Municipality'                    ,'LGMV-Alert-Bay'           ,'Village of Alert Bay'                                 ),
('LG','Municipality'                    ,'LGMV-Anmore'              ,'Village of Anmore'                                    ),
('LG','Municipality'                    ,'LGMV-Ashcroft'            ,'Village of Ashcroft'                                  ),
('LG','Municipality'                    ,'LGMV-Belcarra'            ,'Village of Belcarra'                                  ),
('LG','Municipality'                    ,'LGMV-Burns-Lake'          ,'Village of Burns Lake'                                ),
('LG','Municipality'                    ,'LGMV-Cache-Creek'         ,'Village of Cache Creek'                               ),
('LG','Municipality'                    ,'LGMV-Canal-Flats'         ,'Village of Canal Flats'                               ),
('LG','Municipality'                    ,'LGMV-Chase'               ,'Village of Chase'                                     ),
('LG','Municipality'                    ,'LGMV-Clinton'             ,'Village of Clinton'                                   ),
('LG','Municipality'                    ,'LGMV-Cumberland'          ,'Village of Cumberland'                                ),
('LG','Municipality'                    ,'LGMV-Daajing-Giids'       ,'Village of Daajing Giids'                             ),
('LG','Municipality'                    ,'LGMV-Fraser-Lake'         ,'Village of Fraser Lake'                               ),
('LG','Municipality'                    ,'LGMV-Fruitvale'           ,'Village of Fruitvale'                                 ),
('LG','Municipality'                    ,'LGMV-Gold-River'          ,'Village of Gold River'                                ),
('LG','Municipality'                    ,'LGMV-Granisle'            ,'Village of Granisle'                                  ),
('LG','Municipality'                    ,'LGMV-Harrison-Hot-Springs','Village of Harrison Hot Springs'                      ),
('LG','Municipality'                    ,'LGMV-Hazelton'            ,'Village of Hazelton'                                  ),
('LG','Municipality'                    ,'LGMV-Kaslo'               ,'Village of Kaslo'                                     ),
('LG','Municipality'                    ,'LGMV-Keremeos'            ,'Village of Keremeos'                                  ),
('LG','Municipality'                    ,'LGMV-Lions-Bay'           ,'Village of Lions Bay'                                 ),
('LG','Municipality'                    ,'LGMV-Lumby'               ,'Village of Lumby'                                     ),
('LG','Municipality'                    ,'LGMV-Lytton'              ,'Village of Lytton'                                    ),
('LG','Municipality'                    ,'LGMV-Masset'              ,'Village of Masset'                                    ),
('LG','Municipality'                    ,'LGMV-McBride'             ,'Village of McBride'                                   ),
('LG','Municipality'                    ,'LGMV-Midway'              ,'Village of Midway'                                    ),
('LG','Municipality'                    ,'LGMV-Montrose'            ,'Village of Montrose'                                  ),
('LG','Municipality'                    ,'LGMV-Nakusp'              ,'Village of Nakusp'                                    ),
('LG','Municipality'                    ,'LGMV-New-Denver'          ,'Village of New Denver'                                ),
('LG','Municipality'                    ,'LGMV-Pemberton'           ,'Village of Pemberton'                                 ),
('LG','Municipality'                    ,'LGMV-Port-Alice'          ,'Village of Port Alice'                                ),
('LG','Municipality'                    ,'LGMV-Port-Clements'       ,'Village of Port Clements'                             ),
('LG','Municipality'                    ,'LGMV-Pouce-Coupe'         ,'Village of Pouce Coupe'                               ),
('LG','Municipality'                    ,'LGMV-Radium-Hot-Springs'  ,'Village of Radium Hot Springs'                        ),
('LG','Municipality'                    ,'LGMV-Salmo'               ,'Village of Salmo'                                     ),
('LG','Municipality'                    ,'LGMV-Sayward'             ,'Village of Sayward'                                   ),
('LG','Municipality'                    ,'LGMV-Silverton'           ,'Village of Silverton'                                 ),
('LG','Municipality'                    ,'LGMV-Slocan'              ,'Village of Slocan'                                    ),
('LG','Municipality'                    ,'LGMV-Tahsis'              ,'Village of Tahsis'                                    ),
('LG','Municipality'                    ,'LGMV-Telkwa'              ,'Village of Telkwa'                                    ),
('LG','Municipality'                    ,'LGMV-Valemount'           ,'Village of Valemount'                                 ),
('LG','Municipality'                    ,'LGMV-Warfield'            ,'Village of Warfield'                                  ),
('LG','Municipality'                    ,'LGMV-Zeballos'            ,'Village of Zeballos'                                  ),
('LG','Other'                           ,'LGNILTA-Islands'          ,'Islands Trust'                                        ),
('LG','Other'                           ,'LGNILTA-Salt-Spring'      ,'Salt Spring Island Local Trust Area'                  ),
('LG','Other'                           ,'LGPBC-BC-Parks'           ,'BC Parks'                                             ),
('LG','Regional District Electoral Area','LGRD-Alberni-Clayoquot'   ,'Regional District of Alberni-Clayoquot'               ),
('LG','Regional District Electoral Area','LGRD-Atlin'               ,'Atlin Community Improvement District'                 ),
('LG','Regional District Electoral Area','LGRD-Bulkley-Nechako'     ,'Regional District of Bulkley-Nechako'                 ),
('LG','Regional District Electoral Area','LGRD-Capital'             ,'Capital Regional District'                            ),
('LG','Regional District Electoral Area','LGRD-Cariboo'             ,'Cariboo Regional District'                            ),
('LG','Regional District Electoral Area','LGRD-Central-Coast'       ,'Central Coast Regional District'                      ),
('LG','Regional District Electoral Area','LGRD-Central-Kootenay'    ,'Regional District of Central Kootenay'                ),
('LG','Regional District Electoral Area','LGRD-Central-Okanagan'    ,'Regional District of Central Okanagan'                ),
('LG','Regional District Electoral Area','LGRD-Columbia-Shuswap'    ,'Columbia Shuswap Regional District'                   ),
('LG','Regional District Electoral Area','LGRD-Comox-Valley'        ,'Comox Valley Regional District'                       ),
('LG','Regional District Electoral Area','LGRD-Cowichan-Valley'     ,'Cowichan Valley Regional District'                    ),
('LG','Regional District Electoral Area','LGRD-East-Kootenay'       ,'Regional District of East Kootenay'                   ),
('LG','Regional District Electoral Area','LGRD-Fraser-Fort-George'  ,'Regional District of Fraser-Fort George'              ),
('LG','Regional District Electoral Area','LGRD-Fraser-Valley'       ,'Fraser Valley Regional District'                      ),
('LG','Regional District Electoral Area','LGRD-Kitimat-Stikine'     ,'Regional District of Kitimat-Stikine'                 ),
('LG','Regional District Electoral Area','LGRD-Kootenay-Boundary'   ,'Regional District of Kootenay Boundary'               ),
('LG','Regional District Electoral Area','LGRD-Metro-Vancouver'     ,'Metro Vancouver Regional District'                    ),
('LG','Regional District Electoral Area','LGRD-Mount-Waddington'    ,'Regional District of Mount Waddington'                ),
('LG','Regional District Electoral Area','LGRD-Nanaimo'             ,'Regional District of Nanaimo'                         ),
('LG','Regional District Electoral Area','LGRD-North-Coast'         ,'North Coast Regional District'                        ),
('LG','Regional District Electoral Area','LGRD-North-Okanagan'      ,'Regional District of North Okanagan'                  ),
('LG','Regional District Electoral Area','LGRD-Okanagan-Similkameen','Regional District of Okanagan-Similkameen'            ),
('LG','Regional District Electoral Area','LGRD-Peace-River'         ,'Peace River Regional District'                        ),
('LG','Regional District Electoral Area','LGRD-qathet'              ,'qathet Regional District'                             ),
('LG','Regional District Electoral Area','LGRD-Squamish-Lillooet'   ,'Squamish-Lillooet Regional District'                  ),
('LG','Regional District Electoral Area','LGRD-Strathcona'          ,'Strathcona Regional District'                         ),
('LG','Regional District Electoral Area','LGRD-Sunshine-Coast'      ,'Sunshine Coast Regional District'                     ),
('LG','Regional District Electoral Area','LGRD-Thompson-Nicola'     ,'Thompson-Nicola Regional District'                    ),
('LG','First Nations Community'         ,'LGXFN-Adams-Lake'         ,'Adams Lake Indian Band'                               ),
('LG','First Nations Community'         ,'LGXFN-Ahousaht'           ,'Ahousaht First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Aitchelitz'         ,'Aitchelitz Band'                                      ),
('LG','First Nations Community'         ,'LGXFN-?Akisq-nuk'         ,'?Akisq''nuk First Nation'                             ),
('LG','First Nations Community'         ,'LGXFN-?aqam'              ,'?aqam'                                                ),
('LG','First Nations Community'         ,'LGXFN-Ashcroft'           ,'Ashcroft Indian Band'                                 ),
('LG','First Nations Community'         ,'LGXFN-Binche-Whut-en'     ,'Binche Whut''en First Nation'                         ),
('LG','First Nations Community'         ,'LGXFN-Blueberry-River'    ,'Blueberry River First Nation'                         ),
('LG','First Nations Community'         ,'LGXFN-Bonaparte'          ,'Bonaparte First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Boothroyd'          ,'Boothroyd Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Boston-Bar'         ,'Boston Bar First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Canim-Lake'         ,'Canim Lake Indian Band (Tsq''escen’)'                 ),
('LG','First Nations Community'         ,'LGXFN-Cayoose-Creek'      ,'Cayoose Creek Band (Sekw''el''was)'                   ),
('LG','First Nations Community'         ,'LGXFN-Chawathil'          ,'Chawathil Band'                                       ),
('LG','First Nations Community'         ,'LGXFN-Cheam'              ,'Cheam First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Cheslatta'          ,'Cheslatta Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Coldwater'          ,'Coldwater Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Cooks-Ferry'        ,'Cook''s Ferry Indian Band'                            ),
('LG','First Nations Community'         ,'LGXFN-Cowichan'           ,'Cowichan Tribes'                                      ),
('LG','First Nations Community'         ,'LGXFN-Da-naxda-xw'        ,'Da''naxda''xw First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Dease-River'        ,'Dease River Band Council'                             ),
('LG','First Nations Community'         ,'LGXFN-Ditidaht'           ,'Ditidaht First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Doig-River'         ,'Doig River First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Douglas'            ,'Douglas First Nation (Xa’xtsa)'                       ),
('LG','First Nations Community'         ,'LGXFN-Dzawada-enuxw'      ,'Dzawada''enuxw First Nation'                          ),
('LG','First Nations Community'         ,'LGXFN-Ehattesaht'         ,'Ehattesaht First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-?Esdilagh'          ,'?Esdilagh First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Esk-etemc'          ,'Esk''etemc First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Fort-Nelson'        ,'Fort Nelson First Nation'                             ),
('LG','First Nations Community'         ,'LGXFN-Gitanmaax'          ,'Gitanmaax Band Council'                               ),
('LG','First Nations Community'         ,'LGXFN-Gitanyow'           ,'Gitanyow Hereditary Chiefs'                           ),
('LG','First Nations Community'         ,'LGXFN-Gitga-at'           ,'Gitga''at First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Gitsegukla'         ,'Gitsegukla Indian Band (Kitsegugkla)'                 ),
('LG','First Nations Community'         ,'LGXFN-Gitwangak'          ,'Gitwangak Band Council (Kitwanga)'                    ),
('LG','First Nations Community'         ,'LGXFN-Gitxaala'           ,'Gitxaala Nation (Kitkatla)'                           ),
('LG','First Nations Community'         ,'LGXFN-Glen-Vowell'        ,'Glen Vowell Indian Band (Sik-e-Dakh)'                 ),
('LG','First Nations Community'         ,'LGXFN-Gwa-sala-Nakwaxdaxw','Gwa''sala-''Nakwaxda''xw Nation'                      ),
('LG','First Nations Community'         ,'LGXFN-Gwawaenuk'          ,'Gwawaenuk Tribe'                                      ),
('LG','First Nations Community'         ,'LGXFN-Hagwilget'          ,'Hagwilget Village Council'                            ),
('LG','First Nations Community'         ,'LGXFN-Haisla'             ,'Haisla Nation'                                        ),
('LG','First Nations Community'         ,'LGXFN-Halalt'             ,'Halalt First Nation'                                  ),
('LG','First Nations Community'         ,'LGXFN-Halfway-River'      ,'Halfway River First Nations'                          ),
('LG','First Nations Community'         ,'LGXFN-Heiltsuk'           ,'Heiltsuk Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Hesquiaht'          ,'Hesquiaht First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-High-Bar'           ,'High Bar First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Homalco'            ,'Homalco (Xwemalhkwu) Indian Band'                     ),
('LG','First Nations Community'         ,'LGXFN-Hupa-asath'         ,'Hupa¢asath First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Iskut'              ,'Iskut First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Kanaka'             ,'Kanaka Bar Indian Band'                               ),
('LG','First Nations Community'         ,'LGXFN-Katzie'             ,'Katzie First Nation'                                  ),
('LG','First Nations Community'         ,'LGXFN-Kispiox'            ,'Kispiox Band Council'                                 ),
('LG','First Nations Community'         ,'LGXFN-Kitasoo-Xai-xais'   ,'Kitasoo/Xai''xais Band Council (Klemtu)'              ),
('LG','First Nations Community'         ,'LGXFN-Kitselas'           ,'Kitselas First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Kitsumkalum'        ,'Kitsumkalum First Nation'                             ),
('LG','First Nations Community'         ,'LGXFN-Klahoose'           ,'Klahoose First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-K-omoks'            ,'K’ómoks First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Kwadacha'           ,'Kwadacha Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Kwakiutl'           ,'Kwakiutl Indian Band'                                 ),
('LG','First Nations Community'         ,'LGXFN-Kwantlen'           ,'Kwantlen First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Kwaw-kwaw-Apilt'    ,'Kwaw-kwaw-Apilt First Nation'                         ),
('LG','First Nations Community'         ,'LGXFN-Kwikwasut-inuxw-Hax','Kwikwasut''inuxw Haxwa''mis First Nation'             ),
('LG','First Nations Community'         ,'LGXFN-Kwikwetlem'         ,'Kwikwetlem First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Lake-Babine'        ,'Lake Babine Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Lax-Kw-alaams'      ,'Lax Kw''alaams Indian Band'                           ),
('LG','First Nations Community'         ,'LGXFN-Leq-a-mel'          ,'Leq''a:mel First Nation (Lakahahmen)'                 ),
('LG','First Nations Community'         ,'LGXFN-Lheidli-T-enneh'    ,'Lheidli T''enneh First Nation'                        ),
('LG','First Nations Community'         ,'LGXFN-Lhoosk-uz-Dene'     ,'Lhoosk''uz Dene'' Government Administration (Kluskus)'),
('LG','First Nations Community'         ,'LGXFN-Lhtako-Dene'        ,'Lhtako Dene Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Liard'              ,'Liard First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Lil-wat'            ,'Lil''wat Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Lower-Kootenay'     ,'Lower Kootenay Indian Band (Yaqan nu?kiy)'            ),
('LG','First Nations Community'         ,'LGXFN-Lower-Nicola'       ,'Lower Nicola Indian Band'                             ),
('LG','First Nations Community'         ,'LGXFN-Lower-Similkameen'  ,'Lower Similkameen Indian Band'                        ),
('LG','First Nations Community'         ,'LGXFN-Lyackson'           ,'Lyackson First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Lytton'             ,'Lytton First Nation'                                  ),
('LG','First Nations Community'         ,'LGXFN-Malahat'            ,'Malahat First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Matsqui'            ,'Matsqui First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-McLeod-Lake'        ,'McLeod Lake Indian Band'                              ),
('LG','First Nations Community'         ,'LGXFN-Metlakatla'         ,'Metlakatla First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Mowachaht-Muchalaht','Mowachaht/Muchalaht First Nation'                     ),
('LG','First Nations Community'         ,'LGXFN-Musqueam'           ,'Musqueam Indian Band'                                 ),
('LG','First Nations Community'         ,'LGXFN-Nadleh-Whuten'      ,'Nadleh Whuten Band'                                   ),
('LG','First Nations Community'         ,'LGXFN-Nak-azdli-Whut-en'  ,'Nak''azdli Whut''en'                                  ),
('LG','First Nations Community'         ,'LGXFN-Namgis'             ,'‘Namgis First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Nanoose'            ,'Nanoose First Nation (Snaw-naw-as)'                   ),
('LG','First Nations Community'         ,'LGXFN-Nazko'              ,'Nazko First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Nee-Tahi-Buhn'      ,'Nee-Tahi-Buhn Band'                                   ),
('LG','First Nations Community'         ,'LGXFN-Neskonlith'         ,'Neskonlith Indian Band'                               ),
('LG','First Nations Community'         ,'LGXFN-Nisga-a'            ,'Nisga''a Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Nooaitch'           ,'Nooaitch Indian Band'                                 ),
('LG','First Nations Community'         ,'LGXFN-N-Quatqua'          ,'N''Quatqua First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Nuchatlaht'         ,'Nuchatlaht First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Nuxalk'             ,'Nuxalk Nation'                                        ),
('LG','First Nations Community'         ,'LGXFN-Okanagan'           ,'Okanagan Indian Band'                                 ),
('LG','First Nations Community'         ,'LGXFN-Old-Massett'        ,'Old Massett Village Council'                          ),
('LG','First Nations Community'         ,'LGXFN-Oregon-Jack-Creek'  ,'Oregon Jack Creek Band'                               ),
('LG','First Nations Community'         ,'LGXFN-Osoyoos'            ,'Osoyoos Indian Band'                                  ),
('LG','First Nations Community'         ,'LGXFN-Pacheedaht'         ,'Pacheedaht First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Pauquachin'         ,'Pauquachin First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Penelakut'          ,'Penelakut Tribe'                                      ),
('LG','First Nations Community'         ,'LGXFN-Penticton'          ,'Penticton Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Peters'             ,'Peters Band'                                          ),
('LG','First Nations Community'         ,'LGXFN-Popkum'             ,'Popkum Indian Band'                                   ),
('LG','First Nations Community'         ,'LGXFN-Prophet-River'      ,'Prophet River First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Qualicum'           ,'Qualicum First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Quatsino'           ,'Quatsino First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Saik-uz'            ,'Saik''uz First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Samahquam'          ,'Samahquam First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Saulteau'           ,'Saulteau First Nations'                               ),
('LG','First Nations Community'         ,'LGXFN-Sc-ianew'           ,'Sc''ianew First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Semiahmoo'          ,'Semiahmoo First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Shackan'            ,'Shackan Indian Band'                                  ),
('LG','First Nations Community'         ,'LGXFN-shishalh'           ,'shíshálh Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Shuswap'            ,'Shuswap Band'                                         ),
('LG','First Nations Community'         ,'LGXFN-Shxwha-y'           ,'Shxwhá:y Village'                                     ),
('LG','First Nations Community'         ,'LGXFN-Shxw-ow-hamel'      ,'Shxw''ow''hamel First Nation'                         ),
('LG','First Nations Community'         ,'LGXFN-Simpcw'             ,'Simpcw First Nation'                                  ),
('LG','First Nations Community'         ,'LGXFN-Siska'              ,'Siska Indian Band'                                    ),
('LG','First Nations Community'         ,'LGXFN-Skatin'             ,'Skatin Nations (Skookumchuck)'                        ),
('LG','First Nations Community'         ,'LGXFN-Skawahlook-Sqewalxw','Skawahlook / Sq’ewá:lxw First Nation'                 ),
('LG','First Nations Community'         ,'LGXFN-Skeetchestn'        ,'Skeetchestn Indian Band'                              ),
('LG','First Nations Community'         ,'LGXFN-Skidegate'          ,'Skidegate Band Council'                               ),
('LG','First Nations Community'         ,'LGXFN-Skin-Tyee'          ,'Skin Tyee Band'                                       ),
('LG','First Nations Community'         ,'LGXFN-Skowkale'           ,'Skowkale First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Skuppah'            ,'Skuppah Indian Band'                                  ),
('LG','First Nations Community'         ,'LGXFN-Skwah'              ,'Skwah First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Skwelax-te-Secwepem','Skwelax te Secwepemcelecw'                            ),
('LG','First Nations Community'         ,'LGXFN-Snuneymuxw'         ,'Snuneymuxw First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Songhees'           ,'Songhees Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Soowahlie'          ,'Soowahlie Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Splatsin'           ,'Splatsin Band'                                        ),
('LG','First Nations Community'         ,'LGXFN-Spuzzum'            ,'Spuzzum (Spô’zêm) First Nation'                       ),
('LG','First Nations Community'         ,'LGXFN-Sq-ewlets'          ,'Sq''éwlets First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Sq-ewqel'           ,'Sq’éwqel (Seabird Island Band)'                       ),
('LG','First Nations Community'         ,'LGXFN-Squamish'           ,'Squamish Nation'                                      ),
('LG','First Nations Community'         ,'LGXFN-Squiala'            ,'Squiala First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Stellat-en'         ,'Stellat''en First Nation'                             ),
('LG','First Nations Community'         ,'LGXFN-Sts-ailes'          ,'Sts''ailes Nation'                                    ),
('LG','First Nations Community'         ,'LGXFN-Stswecem-c-Xgat-tem','Stswecem’c Xgat’tem First Nation'                     ),
('LG','First Nations Community'         ,'LGXFN-Stz-uminus'         ,'Stz''uminus First Nation'                             ),
('LG','First Nations Community'         ,'LGXFN-Sumas'              ,'Sumas First Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Tahltan'            ,'Tahltan Band'                                         ),
('LG','First Nations Community'         ,'LGXFN-Takla'              ,'Takla Nation'                                         ),
('LG','First Nations Community'         ,'LGXFN-Taku-River-Tlingit' ,'Taku River Tlingit First Nation'                      ),
('LG','First Nations Community'         ,'LGXFN-T-it-q-et'          ,'T''it''q''et'                                         ),
('LG','First Nations Community'         ,'LGXFN-Tk-emlups-te-Secwep','Tk''emlúps te Secwépemc'                              ),
('LG','First Nations Community'         ,'LGXFN-Tla-o-qui-aht'      ,'Tla-o-qui-aht First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Tlatlasikwala'      ,'Tlatlasikwala'                                        ),
('LG','First Nations Community'         ,'LGXFN-Tl-azt-en'          ,'Tl''azt''en Nation'                                   ),
('LG','First Nations Community'         ,'LGXFN-Tl-etinqox'         ,'Tl''etinqox Government Office'                        ),
('LG','First Nations Community'         ,'LGXFN-Tl-etinqox-t-in'    ,'Tl''etinqox-t''in Government Office'                  ),
('LG','First Nations Community'         ,'LGXFN-Tlowitsis'          ,'Tlowitsis Nation'                                     ),
('LG','First Nations Community'         ,'LGXFN-Tobacco-Plains'     ,'Tobacco Plains Indian Band'                           ),
('LG','First Nations Community'         ,'LGXFN-Toosey'             ,'Toosey Indian Band (Tl''esqox)'                       ),
('LG','First Nations Community'         ,'LGXFN-Tsal-alh'           ,'Tsal''alh'                                            ),
('LG','First Nations Community'         ,'LGXFN-Tsartlip'           ,'Tsartlip First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Tsawout'            ,'Tsawout First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Tsawwassen'         ,'Tsawwassen First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Tsay-Keh-Dene'      ,'Tsay Keh Dene'                                        ),
('LG','First Nations Community'         ,'LGXFN-Tseshaht'           ,'Tseshaht First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Tseycum'            ,'Tseycum First Nation'                                 ),
('LG','First Nations Community'         ,'LGXFN-Tsideldel'          ,'Tŝideldel First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Ts-il-Kaz-Koh'      ,'Ts’il Kaz Koh First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Ts-kw-aylaxw'       ,'Ts''kw''aylaxw First Nation'                          ),
('LG','First Nations Community'         ,'LGXFN-Tsleil-Waututh'     ,'Tsleil-Waututh Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-T-sou-ke'           ,'T''sou-ke Nation'                                     ),
('LG','First Nations Community'         ,'LGXFN-Tsq-escen'          ,'Tsq''escen'' First Nation'                            ),
('LG','First Nations Community'         ,'LGXFN-Ts-uubaa-asatx'     ,'Ts''uubaa-asatx'                                      ),
('LG','First Nations Community'         ,'LGXFN-Tzeachten'          ,'Tzeachten First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Ulkatcho'           ,'Ulkatcho First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Union-Bar'          ,'Union Bar Indian Band'                                ),
('LG','First Nations Community'         ,'LGXFN-Upper-Nicola'       ,'Upper Nicola Band'                                    ),
('LG','First Nations Community'         ,'LGXFN-Upper-Similkameen'  ,'Upper Similkameen Indian Band'                        ),
('LG','First Nations Community'         ,'LGXFN-Westbank'           ,'Westbank First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-West-Moberly'       ,'West Moberly First Nations'                           ),
('LG','First Nations Community'         ,'LGXFN-Wet-suwet-en'       ,'Wet''suwet''en First Nation'                          ),
('LG','First Nations Community'         ,'LGXFN-We-Wai-Kai'         ,'We Wai Kai Nation'                                    ),
('LG','First Nations Community'         ,'LGXFN-We-Wai-Kum'         ,'We Wai Kum First Nation'                              ),
('LG','First Nations Community'         ,'LGXFN-Whispering-Pines-Cl','Whispering Pines/Clinton Indian Band'                 ),
('LG','First Nations Community'         ,'LGXFN-Williams-Lake'      ,'Williams Lake First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Witset'             ,'Witset First Nation'                                  ),
('LG','First Nations Community'         ,'LGXFN-Wuikinuxv'          ,'Wuikinuxv First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Xat-sull'           ,'Xat''sull First Nation'                               ),
('LG','First Nations Community'         ,'LGXFN-Xaxli-p'            ,'Xaxli''p First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Xeni-Gwet-in'       ,'Xeni Gwet''in First Nations Government'               ),
('LG','First Nations Community'         ,'LGXFN-Xwísten'            ,'Xwísten'                                              ),
('LG','First Nations Community'         ,'LGXFN-Yakweakwioose'      ,'Yakweakwioose First Nation'                           ),
('LG','First Nations Community'         ,'LGXFN-Yale'               ,'Yale First Nation'                                    ),
('LG','First Nations Community'         ,'LGXFN-Yekooche'           ,'Yekooche First Nation'                                ),
('LG','First Nations Community'         ,'LGXFN-Yunesit-in'         ,'Yunesit''in First Nation'                             ))
AS s (organization_type, local_government_type, organization_cd, organization_nm)
) AS src
ON (tgt.organization_cd=src.organization_cd)
WHEN matched and (
tgt.organization_nm!=src.organization_nm or
tgt.organization_type!=src.organization_type or
tgt.local_government_type!=src.local_government_type or
tgt.local_government_type is null)
THEN UPDATE SET
organization_nm=src.organization_nm,
organization_type=src.organization_type,
local_government_type=src.local_government_type
WHEN NOT MATCHED
THEN INSERT (organization_type, organization_cd, organization_nm, local_government_type)
VALUES (src.organization_type, src.organization_cd, src.organization_nm, src.local_government_type);
