/* STR DSS Sprint 19 Local Governments Data Seeding */

UPDATE dss_organization set
	is_active=false,
	is_lg_participating=false,
	local_government_type=coalesce(local_government_type,'Other'),
	organization_nm=case when organization_nm like 'z%' then organization_nm else concat('z ',organization_nm) end
where organization_type='LG';

MERGE INTO dss_organization AS tgt
USING ( SELECT * FROM (VALUES
('Municipality'           ,'LGMC_ABBOTSFORD'          ,'City of Abbotsford'                                   ),
('Municipality'           ,'LGMC_ARMSTRONG'           ,'City of Armstrong'                                    ),
('Municipality'           ,'LGMC_BURNABY'             ,'City of Burnaby'                                      ),
('Municipality'           ,'LGMC_CAMPBELL_RIVER'      ,'City of Campbell River'                               ),
('Municipality'           ,'LGMC_CASTLEGAR'           ,'City of Castlegar'                                    ),
('Municipality'           ,'LGMC_CHILLIWACK'          ,'City of Chilliwack'                                   ),
('Municipality'           ,'LGMC_COLWOOD'             ,'City of Colwood'                                      ),
('Municipality'           ,'LGMC_COQUITLAM'           ,'City of Coquitlam'                                    ),
('Municipality'           ,'LGMC_COURTENAY'           ,'City of Courtenay'                                    ),
('Municipality'           ,'LGMC_CRANBROOK'           ,'City of Cranbrook'                                    ),
('Municipality'           ,'LGMC_DAWSON_CREEK'        ,'City of Dawson Creek'                                 ),
('Municipality'           ,'LGMC_DELTA'               ,'City of Delta'                                        ),
('Municipality'           ,'LGMC_DUNCAN'              ,'City of Duncan'                                       ),
('Municipality'           ,'LGMC_ENDERBY'             ,'City of Enderby'                                      ),
('Municipality'           ,'LGMC_FERNIE'              ,'City of Fernie'                                       ),
('Municipality'           ,'LGMC_FORT_ST_JOHN'        ,'City of Fort St John'                                 ),
('Municipality'           ,'LGMC_GRAND_FORKS'         ,'City of Grand Forks'                                  ),
('Municipality'           ,'LGMC_GREENWOOD'           ,'City of Greenwood'                                    ),
('Municipality'           ,'LGMC_KAMLOOPS'            ,'City of Kamloops'                                     ),
('Municipality'           ,'LGMC_KELOWNA'             ,'City of Kelowna'                                      ),
('Municipality'           ,'LGMC_KIMBERLEY'           ,'City of Kimberley'                                    ),
('Municipality'           ,'LGMC_LANGFORD'            ,'City of Langford'                                     ),
('Municipality'           ,'LGMC_LANGLEY'             ,'City of Langley'                                      ),
('Municipality'           ,'LGMC_MAPLE_RIDGE'         ,'City of Maple Ridge'                                  ),
('Municipality'           ,'LGMC_MERRITT'             ,'City of Merritt'                                      ),
('Municipality'           ,'LGMC_MISSION'             ,'City of Mission'                                      ),
('Municipality'           ,'LGMC_NANAIMO'             ,'City of Nanaimo'                                      ),
('Municipality'           ,'LGMC_NELSON'              ,'City of Nelson'                                       ),
('Municipality'           ,'LGMC_NEW_WESTMINSTER'     ,'City of New Westminster'                              ),
('Municipality'           ,'LGMC_NORTH_VANCOUVER'     ,'City of North Vancouver'                              ),
('Municipality'           ,'LGMC_PARKSVILLE'          ,'City of Parksville'                                   ),
('Municipality'           ,'LGMC_PENTICTON'           ,'City of Penticton'                                    ),
('Municipality'           ,'LGMC_PITT_MEADOWS'        ,'City of Pitt Meadows'                                 ),
('Municipality'           ,'LGMC_PORT_ALBERNI'        ,'City of Port Alberni'                                 ),
('Municipality'           ,'LGMC_PORT_COQUITLAM'      ,'City of Port Coquitlam'                               ),
('Municipality'           ,'LGMC_PORT_MOODY'          ,'City of Port Moody'                                   ),
('Municipality'           ,'LGMC_POWELL_RIVER'        ,'City of Powell River'                                 ),
('Municipality'           ,'LGMC_PRINCE_GEORGE'       ,'City of Prince George'                                ),
('Municipality'           ,'LGMC_PRINCE_RUPERT'       ,'City of Prince Rupert'                                ),
('Municipality'           ,'LGMC_QUESNEL'             ,'City of Quesnel'                                      ),
('Municipality'           ,'LGMC_REVELSTOKE'          ,'City of Revelstoke'                                   ),
('Municipality'           ,'LGMC_RICHMOND'            ,'City of Richmond'                                     ),
('Municipality'           ,'LGMC_ROSSLAND'            ,'City of Rossland'                                     ),
('Municipality'           ,'LGMC_SALMON_ARM'          ,'City of Salmon Arm'                                   ),
('Municipality'           ,'LGMC_SURREY'              ,'City of Surrey'                                       ),
('Municipality'           ,'LGMC_TERRACE'             ,'City of Terrace'                                      ),
('Municipality'           ,'LGMC_TRAIL'               ,'City of Trail'                                        ),
('Municipality'           ,'LGMC_VANCOUVER'           ,'City of Vancouver'                                    ),
('Municipality'           ,'LGMC_VERNON'              ,'City of Vernon'                                       ),
('Municipality'           ,'LGMC_VICTORIA'            ,'City of Victoria'                                     ),
('Municipality'           ,'LGMC_WEST_KELOWNA'        ,'City of West Kelowna'                                 ),
('Municipality'           ,'LGMC_WHITE_ROCK'          ,'City of White Rock'                                   ),
('Municipality'           ,'LGMC_WILLIAMS_LAKE'       ,'City of Williams Lake'                                ),
('Municipality'           ,'LGMD_WEST_VANCOUVER'      ,'District Municipality of West Vancouver'              ),
('Municipality'           ,'LGMD_100_MILE_HOUSE'      ,'District of 100 Mile House'                           ),
('Municipality'           ,'LGMD_BARRIERE'            ,'District of Barriere'                                 ),
('Municipality'           ,'LGMD_CENTRAL_SAANICH'     ,'District of Central Saanich'                          ),
('Municipality'           ,'LGMD_CHETWYND'            ,'District of Chetwynd'                                 ),
('Municipality'           ,'LGMD_CLEARWATER'          ,'District of Clearwater'                               ),
('Municipality'           ,'LGMD_COLDSTREAM'          ,'District of Coldstream'                               ),
('Municipality'           ,'LGMD_ELKFORD'             ,'District of Elkford'                                  ),
('Municipality'           ,'LGMD_FORT_ST_JAMES'       ,'District of Fort St James'                            ),
('Municipality'           ,'LGMD_HIGHLANDS'           ,'District of Highlands'                                ),
('Municipality'           ,'LGMD_HOPE'                ,'District of Hope'                                     ),
('Municipality'           ,'LGMD_HOUSTON'             ,'District of Houston'                                  ),
('Municipality'           ,'LGMD_HUDSONS_HOPE'        ,'District of Hudsons Hope'                             ),
('Municipality'           ,'LGMD_INVERMERE'           ,'District of Invermere'                                ),
('Municipality'           ,'LGMD_KENT'                ,'District of Kent'                                     ),
('Municipality'           ,'LGMD_KITIMAT'             ,'District of Kitimat'                                  ),
('Municipality'           ,'LGMD_LAKE_COUNTRY'        ,'District of Lake Country'                             ),
('Municipality'           ,'LGMD_LANTZVILLE'          ,'District of Lantzville'                               ),
('Municipality'           ,'LGMD_LILLOOET'            ,'District of Lillooet'                                 ),
('Municipality'           ,'LGMD_LOGAN_LAKE'          ,'District of Logan Lake'                               ),
('Municipality'           ,'LGMD_MACKENZIE'           ,'District of Mackenzie'                                ),
('Municipality'           ,'LGMD_METCHOSIN'           ,'District of Metchosin'                                ),
('Municipality'           ,'LGMD_NEW_HAZELTON'        ,'District of New Hazelton'                             ),
('Municipality'           ,'LGMD_NORTH_COWICHAN'      ,'District of North Cowichan'                           ),
('Municipality'           ,'LGMD_NORTH_SAANICH'       ,'District of North Saanich'                            ),
('Municipality'           ,'LGMD_NORTH_VANCOUVER'     ,'District of North Vancouver'                          ),
('Municipality'           ,'LGMD_OAK_BAY'             ,'District of Oak Bay'                                  ),
('Municipality'           ,'LGMD_PEACHLAND'           ,'District of Peachland'                                ),
('Municipality'           ,'LGMD_PORT_EDWARD'         ,'District of Port Edward'                              ),
('Municipality'           ,'LGMD_PORT_HARDY'          ,'District of Port Hardy'                               ),
('Municipality'           ,'LGMD_SAANICH'             ,'District of Saanich'                                  ),
('Municipality'           ,'LGMD_SECHELT'             ,'District of Sechelt'                                  ),
('Municipality'           ,'LGMD_SICAMOUS'            ,'District of Sicamous'                                 ),
('Municipality'           ,'LGMD_SOOKE'               ,'District of Sooke'                                    ),
('Municipality'           ,'LGMD_SPARWOOD'            ,'District of Sparwood'                                 ),
('Municipality'           ,'LGMD_SQUAMISH'            ,'District of Squamish'                                 ),
('Municipality'           ,'LGMD_STEWART'             ,'District of Stewart'                                  ),
('Municipality'           ,'LGMD_SUMMERLAND'          ,'District of Summerland'                               ),
('Municipality'           ,'LGMD_TAYLOR'              ,'District of Taylor'                                   ),
('Municipality'           ,'LGMD_TOFINO'              ,'District of Tofino'                                   ),
('Municipality'           ,'LGMD_TUMBLER_RIDGE'       ,'District of Tumbler Ridge'                            ),
('Municipality'           ,'LGMD_UCLUELET'            ,'District of Ucluelet'                                 ),
('Municipality'           ,'LGMD_VANDERHOOF'          ,'District of Vanderhoof'                               ),
('Municipality'           ,'LGMD_WELLS'               ,'District of Wells'                                    ),
('Municipality'           ,'LGMI_BOWEN'               ,'Bowen Island Municipality'                            ),
('Municipality'           ,'LGMR_NORTHERN_ROCKIES'    ,'Northern Rockies Regional Municipality'               ),
('Municipality'           ,'LGMR_SUN_PEAKS_MOUNTAIN'  ,'Sun Peaks Mountain Resort Municipality'               ),
('Municipality'           ,'LGMR_WHISTLER'            ,'Resort Municipality of Whistler'                      ),
('Municipality'           ,'LGMT_COMOX'               ,'Town of Comox'                                        ),
('Municipality'           ,'LGMT_CRESTON'             ,'Town of Creston'                                      ),
('Municipality'           ,'LGMT_ESQUIMALT'           ,'Township of Esquimalt'                                ),
('Municipality'           ,'LGMT_GIBSONS'             ,'Town of Gibsons'                                      ),
('Municipality'           ,'LGMT_GOLDEN'              ,'Town of Golden'                                       ),
('Municipality'           ,'LGMT_LADYSMITH'           ,'Town of Ladysmith'                                    ),
('Municipality'           ,'LGMT_LAKE_COWICHAN'       ,'Town of Lake Cowichan'                                ),
('Municipality'           ,'LGMT_LANGLEY'             ,'Township of Langley'                                  ),
('Municipality'           ,'LGMT_OLIVER'              ,'Town of Oliver'                                       ),
('Municipality'           ,'LGMT_OSOYOOS'             ,'Town of Osoyoos'                                      ),
('Municipality'           ,'LGMT_PORT_MCNEILL'        ,'Town of Port McNeill'                                 ),
('Municipality'           ,'LGMT_PRINCETON'           ,'Town of Princeton'                                    ),
('Municipality'           ,'LGMT_QUALICUM_BEACH'      ,'Town of Qualicum Beach'                               ),
('Municipality'           ,'LGMT_SIDNEY'              ,'Town of Sidney'                                       ),
('Municipality'           ,'LGMT_SMITHERS'            ,'Town of Smithers'                                     ),
('Municipality'           ,'LGMT_SPALLUMCHEEN'        ,'Township of Spallumcheen'                             ),
('Municipality'           ,'LGMT_VIEW_ROYAL'          ,'Town of View Royal'                                   ),
('Municipality'           ,'LGMV_ALERT_BAY'           ,'Village of Alert Bay'                                 ),
('Municipality'           ,'LGMV_ANMORE'              ,'Village of Anmore'                                    ),
('Municipality'           ,'LGMV_ASHCROFT'            ,'Village of Ashcroft'                                  ),
('Municipality'           ,'LGMV_BELCARRA'            ,'Village of Belcarra'                                  ),
('Municipality'           ,'LGMV_BURNS_LAKE'          ,'Village of Burns Lake'                                ),
('Municipality'           ,'LGMV_CACHE_CREEK'         ,'Village of Cache Creek'                               ),
('Municipality'           ,'LGMV_CANAL_FLATS'         ,'Village of Canal Flats'                               ),
('Municipality'           ,'LGMV_CHASE'               ,'Village of Chase'                                     ),
('Municipality'           ,'LGMV_CLINTON'             ,'Village of Clinton'                                   ),
('Municipality'           ,'LGMV_CUMBERLAND'          ,'Village of Cumberland'                                ),
('Municipality'           ,'LGMV_DAAJING_GIIDS'       ,'Village of Daajing Giids'                             ),
('Municipality'           ,'LGMV_FRASER_LAKE'         ,'Village of Fraser Lake'                               ),
('Municipality'           ,'LGMV_FRUITVALE'           ,'Village of Fruitvale'                                 ),
('Municipality'           ,'LGMV_GOLD_RIVER'          ,'Village of Gold River'                                ),
('Municipality'           ,'LGMV_GRANISLE'            ,'Village of Granisle'                                  ),
('Municipality'           ,'LGMV_HARRISON_HOT_SPRINGS','Village of Harrison Hot Springs'                      ),
('Municipality'           ,'LGMV_HAZELTON'            ,'Village of Hazelton'                                  ),
('Municipality'           ,'LGMV_KASLO'               ,'Village of Kaslo'                                     ),
('Municipality'           ,'LGMV_KEREMEOS'            ,'Village of Keremeos'                                  ),
('Municipality'           ,'LGMV_LIONS_BAY'           ,'Village of Lions Bay'                                 ),
('Municipality'           ,'LGMV_LUMBY'               ,'Village of Lumby'                                     ),
('Municipality'           ,'LGMV_LYTTON'              ,'Village of Lytton'                                    ),
('Municipality'           ,'LGMV_MASSET'              ,'Village of Masset'                                    ),
('Municipality'           ,'LGMV_MCBRIDE'             ,'Village of McBride'                                   ),
('Municipality'           ,'LGMV_MIDWAY'              ,'Village of Midway'                                    ),
('Municipality'           ,'LGMV_MONTROSE'            ,'Village of Montrose'                                  ),
('Municipality'           ,'LGMV_NAKUSP'              ,'Village of Nakusp'                                    ),
('Municipality'           ,'LGMV_NEW_DENVER'          ,'Village of New Denver'                                ),
('Municipality'           ,'LGMV_PEMBERTON'           ,'Village of Pemberton'                                 ),
('Municipality'           ,'LGMV_PORT_ALICE'          ,'Village of Port Alice'                                ),
('Municipality'           ,'LGMV_PORT_CLEMENTS'       ,'Village of Port Clements'                             ),
('Municipality'           ,'LGMV_POUCE_COUPE'         ,'Village of Pouce Coupe'                               ),
('Municipality'           ,'LGMV_RADIUM_HOT_SPRINGS'  ,'Village of Radium Hot Springs'                        ),
('Municipality'           ,'LGMV_SALMO'               ,'Village of Salmo'                                     ),
('Municipality'           ,'LGMV_SAYWARD'             ,'Village of Sayward'                                   ),
('Municipality'           ,'LGMV_SILVERTON'           ,'Village of Silverton'                                 ),
('Municipality'           ,'LGMV_SLOCAN'              ,'Village of Slocan'                                    ),
('Municipality'           ,'LGMV_TAHSIS'              ,'Village of Tahsis'                                    ),
('Municipality'           ,'LGMV_TELKWA'              ,'Village of Telkwa'                                    ),
('Municipality'           ,'LGMV_VALEMOUNT'           ,'Village of Valemount'                                 ),
('Municipality'           ,'LGMV_WARFIELD'            ,'Village of Warfield'                                  ),
('Municipality'           ,'LGMV_ZEBALLOS'            ,'Village of Zeballos'                                  ),
('Other'                  ,'LGNILTA_ISLANDS'          ,'Islands Trust'                                        ),
('Other'                  ,'LGNILTA_SALT_SPRING'      ,'Salt Spring Island Local Trust Area'                  ),
('Other'                  ,'LGNONE'                   ,'Unassigned Land Parcels'                              ),
('Other'                  ,'LGPBC_BC_PARKS'           ,'BC Parks'                                             ),
('Regional District'      ,'LGRD_ALBERNI_CLAYOQUOT'   ,'Regional District of Alberni-Clayoquot'               ),
('Regional District'      ,'LGRD_ATLIN'               ,'Atlin Community Improvement District'                 ),
('Regional District'      ,'LGRD_BULKLEY_NECHAKO'     ,'Regional District of Bulkley-Nechako'                 ),
('Regional District'      ,'LGRD_CAPITAL'             ,'Capital Regional District'                            ),
('Regional District'      ,'LGRD_CARIBOO'             ,'Cariboo Regional District'                            ),
('Regional District'      ,'LGRD_CENTRAL_COAST'       ,'Central Coast Regional District'                      ),
('Regional District'      ,'LGRD_CENTRAL_KOOTENAY'    ,'Regional District of Central Kootenay'                ),
('Regional District'      ,'LGRD_CENTRAL_OKANAGAN'    ,'Regional District of Central Okanagan'                ),
('Regional District'      ,'LGRD_COLUMBIA_SHUSWAP'    ,'Columbia Shuswap Regional District'                   ),
('Regional District'      ,'LGRD_COMOX_VALLEY'        ,'Comox Valley Regional District'                       ),
('Regional District'      ,'LGRD_COWICHAN_VALLEY'     ,'Cowichan Valley Regional District'                    ),
('Regional District'      ,'LGRD_EAST_KOOTENAY'       ,'Regional District of East Kootenay'                   ),
('Regional District'      ,'LGRD_FRASER_FORT_GEORGE'  ,'Regional District of Fraser-Fort George'              ),
('Regional District'      ,'LGRD_FRASER_VALLEY'       ,'Fraser Valley Regional District'                      ),
('Regional District'      ,'LGRD_KITIMAT_STIKINE'     ,'Regional District of Kitimat-Stikine'                 ),
('Regional District'      ,'LGRD_KOOTENAY_BOUNDARY'   ,'Regional District of Kootenay Boundary'               ),
('Regional District'      ,'LGRD_METRO_VANCOUVER'     ,'Metro Vancouver Regional District'                    ),
('Regional District'      ,'LGRD_MOUNT_WADDINGTON'    ,'Regional District of Mount Waddington'                ),
('Regional District'      ,'LGRD_NANAIMO'             ,'Regional District of Nanaimo'                         ),
('Regional District'      ,'LGRD_NORTH_COAST'         ,'North Coast Regional District'                        ),
('Regional District'      ,'LGRD_NORTH_OKANAGAN'      ,'Regional District of North Okanagan'                  ),
('Regional District'      ,'LGRD_OKANAGAN_SIMILKAMEEN','Regional District of Okanagan-Similkameen'            ),
('Regional District'      ,'LGRD_PEACE_RIVER'         ,'Peace River Regional District'                        ),
('Regional District'      ,'LGRD_QATHET'              ,'qathet Regional District'                             ),
('Regional District'      ,'LGRD_SQUAMISH_LILLOOET'   ,'Squamish-Lillooet Regional District'                  ),
('Regional District'      ,'LGRD_STRATHCONA'          ,'Strathcona Regional District'                         ),
('Regional District'      ,'LGRD_SUNSHINE_COAST'      ,'Sunshine Coast Regional District'                     ),
('Regional District'      ,'LGRD_THOMPSON_NICOLA'     ,'Thompson-Nicola Regional District'                    ),
('First Nations Community','LGXFN_HUU_AY_AHT'         ,'Huu-ay-aht First Nations'                             ),
('First Nations Community','LGXFN_KA_YU_K_T_H'        ,'Ka:''yu:''k''t''h''/Che:k''tles7et''h'' First Nations'),
('First Nations Community','LGXFN_NISGA_A'            ,'Nisga''a Nation'                                      ),
('First Nations Community','LGXFN_RESERVE'            ,'First Nation Reserve Lands'                           ),
('First Nations Community','LGXFN_SHISHALH'           ,'shíshálh Nation'                                      ),
('First Nations Community','LGXFN_TLA_AMIN'           ,'Tla''amin Nation'                                     ),
('First Nations Community','LGXFN_TOQUAHT'            ,'Toquaht Nation'                                       ),
('First Nations Community','LGXFN_TSAWWASSEN'         ,'Tsawwassen First Nation'                              ),
('First Nations Community','LGXFN_UCHUCKLESAHT'       ,'Uchucklesaht Tribe'                                   ),
('First Nations Community','LGXFN_UCLUELET'           ,'Ucluelet First Nation'                                ))
AS s (local_government_type, organization_cd, organization_nm)
) AS src
ON (tgt.organization_cd=UPPER(src.organization_cd))
WHEN matched and (
	coalesce(tgt.is_active, false) != true or
	coalesce(tgt.is_lg_participating, false) != true or
	tgt.organization_nm!=src.organization_nm or
	tgt.organization_type!='LG' or
	tgt.local_government_type!=src.local_government_type or
	tgt.local_government_type is null)
THEN UPDATE SET
	is_active = true,
	is_lg_participating = true,
	organization_nm=src.organization_nm,
	organization_type='LG',
	local_government_type=src.local_government_type
WHEN NOT MATCHED
THEN INSERT (is_active, is_lg_participating, organization_type, organization_cd, organization_nm, local_government_type)
VALUES (true, true, 'LG', src.organization_cd, src.organization_nm, src.local_government_type);
