/* STR DSS Sprint 16 Local Governments Data Seeding */

UPDATE dss_organization
set organization_cd=translate(organization_cd,'-Í','_I')
where organization_cd!=translate(organization_cd,'-Í','_I')
  and organization_type='LG';

MERGE INTO dss_organization AS tgt
USING ( SELECT * FROM (VALUES
('Municipality'                    ,'LGMC_ABBOTSFORD'          ,'City of Abbotsford'                                   ),
('Municipality'                    ,'LGMC_ARMSTRONG'           ,'City of Armstrong'                                    ),
('Municipality'                    ,'LGMC_BURNABY'             ,'City of Burnaby'                                      ),
('Municipality'                    ,'LGMC_CAMPBELL_RIVER'      ,'City of Campbell River'                               ),
('Municipality'                    ,'LGMC_CASTLEGAR'           ,'City of Castlegar'                                    ),
('Municipality'                    ,'LGMC_CHILLIWACK'          ,'City of Chilliwack'                                   ),
('Municipality'                    ,'LGMC_COLWOOD'             ,'City of Colwood'                                      ),
('Municipality'                    ,'LGMC_COQUITLAM'           ,'City of Coquitlam'                                    ),
('Municipality'                    ,'LGMC_COURTENAY'           ,'City of Courtenay'                                    ),
('Municipality'                    ,'LGMC_CRANBROOK'           ,'City of Cranbrook'                                    ),
('Municipality'                    ,'LGMC_DAWSON_CREEK'        ,'City of Dawson Creek'                                 ),
('Municipality'                    ,'LGMC_DELTA'               ,'City of Delta'                                        ),
('Municipality'                    ,'LGMC_DUNCAN'              ,'City of Duncan'                                       ),
('Municipality'                    ,'LGMC_ENDERBY'             ,'City of Enderby'                                      ),
('Municipality'                    ,'LGMC_FERNIE'              ,'City of Fernie'                                       ),
('Municipality'                    ,'LGMC_FORT_ST_JOHN'        ,'City of Fort St John'                                 ),
('Municipality'                    ,'LGMC_GRAND_FORKS'         ,'City of Grand Forks'                                  ),
('Municipality'                    ,'LGMC_GREENWOOD'           ,'City of Greenwood'                                    ),
('Municipality'                    ,'LGMC_KAMLOOPS'            ,'City of Kamloops'                                     ),
('Municipality'                    ,'LGMC_KELOWNA'             ,'City of Kelowna'                                      ),
('Municipality'                    ,'LGMC_KIMBERLEY'           ,'City of Kimberley'                                    ),
('Municipality'                    ,'LGMC_LANGFORD'            ,'City of Langford'                                     ),
('Municipality'                    ,'LGMC_LANGLEY'             ,'City of Langley'                                      ),
('Municipality'                    ,'LGMC_MAPLE_RIDGE'         ,'City of Maple Ridge'                                  ),
('Municipality'                    ,'LGMC_MERRITT'             ,'City of Merritt'                                      ),
('Municipality'                    ,'LGMC_MISSION'             ,'City of Mission'                                      ),
('Municipality'                    ,'LGMC_NANAIMO'             ,'City of Nanaimo'                                      ),
('Municipality'                    ,'LGMC_NELSON'              ,'City of Nelson'                                       ),
('Municipality'                    ,'LGMC_NEW_WESTMINSTER'     ,'City of New Westminster'                              ),
('Municipality'                    ,'LGMC_NORTH_VANCOUVER'     ,'City of North Vancouver'                              ),
('Municipality'                    ,'LGMC_PARKSVILLE'          ,'City of Parksville'                                   ),
('Municipality'                    ,'LGMC_PENTICTON'           ,'City of Penticton'                                    ),
('Municipality'                    ,'LGMC_PITT_MEADOWS'        ,'City of Pitt Meadows'                                 ),
('Municipality'                    ,'LGMC_PORT_ALBERNI'        ,'City of Port Alberni'                                 ),
('Municipality'                    ,'LGMC_PORT_COQUITLAM'      ,'City of Port Coquitlam'                               ),
('Municipality'                    ,'LGMC_PORT_MOODY'          ,'City of Port Moody'                                   ),
('Municipality'                    ,'LGMC_POWELL_RIVER'        ,'City of Powell River'                                 ),
('Municipality'                    ,'LGMC_PRINCE_GEORGE'       ,'City of Prince George'                                ),
('Municipality'                    ,'LGMC_PRINCE_RUPERT'       ,'City of Prince Rupert'                                ),
('Municipality'                    ,'LGMC_QUESNEL'             ,'City of Quesnel'                                      ),
('Municipality'                    ,'LGMC_REVELSTOKE'          ,'City of Revelstoke'                                   ),
('Municipality'                    ,'LGMC_RICHMOND'            ,'City of Richmond'                                     ),
('Municipality'                    ,'LGMC_ROSSLAND'            ,'City of Rossland'                                     ),
('Municipality'                    ,'LGMC_SALMON_ARM'          ,'City of Salmon Arm'                                   ),
('Municipality'                    ,'LGMC_SURREY'              ,'City of Surrey'                                       ),
('Municipality'                    ,'LGMC_TERRACE'             ,'City of Terrace'                                      ),
('Municipality'                    ,'LGMC_TRAIL'               ,'City of Trail'                                        ),
('Municipality'                    ,'LGMC_VANCOUVER'           ,'City of Vancouver'                                    ),
('Municipality'                    ,'LGMC_VERNON'              ,'City of Vernon'                                       ),
('Municipality'                    ,'LGMC_VICTORIA'            ,'City of Victoria'                                     ),
('Municipality'                    ,'LGMC_WEST_KELOWNA'        ,'City of West Kelowna'                                 ),
('Municipality'                    ,'LGMC_WHITE_ROCK'          ,'City of White Rock'                                   ),
('Municipality'                    ,'LGMC_WILLIAMS_LAKE'       ,'City of Williams Lake'                                ),
('Municipality'                    ,'LGMD_WEST_VANCOUVER'      ,'District Municipality of West Vancouver'              ),
('Municipality'                    ,'LGMD_100_MILE_HOUSE'      ,'District of 100 Mile House'                           ),
('Municipality'                    ,'LGMD_BARRIERE'            ,'District of Barriere'                                 ),
('Municipality'                    ,'LGMD_CENTRAL_SAANICH'     ,'District of Central Saanich'                          ),
('Municipality'                    ,'LGMD_CHETWYND'            ,'District of Chetwynd'                                 ),
('Municipality'                    ,'LGMD_CLEARWATER'          ,'District of Clearwater'                               ),
('Municipality'                    ,'LGMD_COLDSTREAM'          ,'District of Coldstream'                               ),
('Municipality'                    ,'LGMD_ELKFORD'             ,'District of Elkford'                                  ),
('Municipality'                    ,'LGMD_FORT_ST_JAMES'       ,'District of Fort St James'                            ),
('Municipality'                    ,'LGMD_HIGHLANDS'           ,'District of Highlands'                                ),
('Municipality'                    ,'LGMD_HOPE'                ,'District of Hope'                                     ),
('Municipality'                    ,'LGMD_HOUSTON'             ,'District of Houston'                                  ),
('Municipality'                    ,'LGMD_HUDSONS_HOPE'        ,'District of Hudsons Hope'                             ),
('Municipality'                    ,'LGMD_INVERMERE'           ,'District of Invermere'                                ),
('Municipality'                    ,'LGMD_KENT'                ,'District of Kent'                                     ),
('Municipality'                    ,'LGMD_KITIMAT'             ,'District of Kitimat'                                  ),
('Municipality'                    ,'LGMD_LAKE_COUNTRY'        ,'District of Lake Country'                             ),
('Municipality'                    ,'LGMD_LANTZVILLE'          ,'District of Lantzville'                               ),
('Municipality'                    ,'LGMD_LILLOOET'            ,'District of Lillooet'                                 ),
('Municipality'                    ,'LGMD_LOGAN_LAKE'          ,'District of Logan Lake'                               ),
('Municipality'                    ,'LGMD_MACKENZIE'           ,'District of Mackenzie'                                ),
('Municipality'                    ,'LGMD_METCHOSIN'           ,'District of Metchosin'                                ),
('Municipality'                    ,'LGMD_NEW_HAZELTON'        ,'District of New Hazelton'                             ),
('Municipality'                    ,'LGMD_NORTH_COWICHAN'      ,'District of North Cowichan'                           ),
('Municipality'                    ,'LGMD_NORTH_SAANICH'       ,'District of North Saanich'                            ),
('Municipality'                    ,'LGMD_NORTH_VANCOUVER'     ,'District of North Vancouver'                          ),
('Municipality'                    ,'LGMD_OAK_BAY'             ,'District of Oak Bay'                                  ),
('Municipality'                    ,'LGMD_PEACHLAND'           ,'District of Peachland'                                ),
('Municipality'                    ,'LGMD_PORT_EDWARD'         ,'District of Port Edward'                              ),
('Municipality'                    ,'LGMD_PORT_HARDY'          ,'District of Port Hardy'                               ),
('Municipality'                    ,'LGMD_SAANICH'             ,'District of Saanich'                                  ),
('Municipality'                    ,'LGMD_SECHELT'             ,'District of Sechelt'                                  ),
('Municipality'                    ,'LGMD_SICAMOUS'            ,'District of Sicamous'                                 ),
('Municipality'                    ,'LGMD_SOOKE'               ,'District of Sooke'                                    ),
('Municipality'                    ,'LGMD_SPARWOOD'            ,'District of Sparwood'                                 ),
('Municipality'                    ,'LGMD_SQUAMISH'            ,'District of Squamish'                                 ),
('Municipality'                    ,'LGMD_STEWART'             ,'District of Stewart'                                  ),
('Municipality'                    ,'LGMD_SUMMERLAND'          ,'District of Summerland'                               ),
('Municipality'                    ,'LGMD_TAYLOR'              ,'District of Taylor'                                   ),
('Municipality'                    ,'LGMD_TOFINO'              ,'District of Tofino'                                   ),
('Municipality'                    ,'LGMD_TUMBLER_RIDGE'       ,'District of Tumbler Ridge'                            ),
('Municipality'                    ,'LGMD_UCLUELET'            ,'District of Ucluelet'                                 ),
('Municipality'                    ,'LGMD_VANDERHOOF'          ,'District of Vanderhoof'                               ),
('Municipality'                    ,'LGMD_WELLS'               ,'District of Wells'                                    ),
('Municipality'                    ,'LGMI_BOWEN'               ,'Bowen Island Municipality'                            ),
('Municipality'                    ,'LGMR_NORTHERN_ROCKIES'    ,'Northern Rockies Regional Municipality'               ),
('Municipality'                    ,'LGMR_SUN_PEAKS_MOUNTAIN'  ,'Sun Peaks Mountain Resort Municipality'               ),
('Municipality'                    ,'LGMR_WHISTLER'            ,'Resort Municipality of Whistler'                      ),
('Municipality'                    ,'LGMT_COMOX'               ,'Town of Comox'                                        ),
('Municipality'                    ,'LGMT_CRESTON'             ,'Town of Creston'                                      ),
('Municipality'                    ,'LGMT_ESQUIMALT'           ,'Township of Esquimalt'                                ),
('Municipality'                    ,'LGMT_GIBSONS'             ,'Town of Gibsons'                                      ),
('Municipality'                    ,'LGMT_GOLDEN'              ,'Town of Golden'                                       ),
('Municipality'                    ,'LGMT_LADYSMITH'           ,'Town of Ladysmith'                                    ),
('Municipality'                    ,'LGMT_LAKE_COWICHAN'       ,'Town of Lake Cowichan'                                ),
('Municipality'                    ,'LGMT_LANGLEY'             ,'Township of Langley'                                  ),
('Municipality'                    ,'LGMT_OLIVER'              ,'Town of Oliver'                                       ),
('Municipality'                    ,'LGMT_OSOYOOS'             ,'Town of Osoyoos'                                      ),
('Municipality'                    ,'LGMT_PORT_MCNEILL'        ,'Town of Port McNeill'                                 ),
('Municipality'                    ,'LGMT_PRINCETON'           ,'Town of Princeton'                                    ),
('Municipality'                    ,'LGMT_QUALICUM_BEACH'      ,'Town of Qualicum Beach'                               ),
('Municipality'                    ,'LGMT_SIDNEY'              ,'Town of Sidney'                                       ),
('Municipality'                    ,'LGMT_SMITHERS'            ,'Town of Smithers'                                     ),
('Municipality'                    ,'LGMT_SPALLUMCHEEN'        ,'Township of Spallumcheen'                             ),
('Municipality'                    ,'LGMT_VIEW_ROYAL'          ,'Town of View Royal'                                   ),
('Municipality'                    ,'LGMV_ALERT_BAY'           ,'Village of Alert Bay'                                 ),
('Municipality'                    ,'LGMV_ANMORE'              ,'Village of Anmore'                                    ),
('Municipality'                    ,'LGMV_ASHCROFT'            ,'Village of Ashcroft'                                  ),
('Municipality'                    ,'LGMV_BELCARRA'            ,'Village of Belcarra'                                  ),
('Municipality'                    ,'LGMV_BURNS_LAKE'          ,'Village of Burns Lake'                                ),
('Municipality'                    ,'LGMV_CACHE_CREEK'         ,'Village of Cache Creek'                               ),
('Municipality'                    ,'LGMV_CANAL_FLATS'         ,'Village of Canal Flats'                               ),
('Municipality'                    ,'LGMV_CHASE'               ,'Village of Chase'                                     ),
('Municipality'                    ,'LGMV_CLINTON'             ,'Village of Clinton'                                   ),
('Municipality'                    ,'LGMV_CUMBERLAND'          ,'Village of Cumberland'                                ),
('Municipality'                    ,'LGMV_DAAJING_GIIDS'       ,'Village of Daajing Giids'                             ),
('Municipality'                    ,'LGMV_FRASER_LAKE'         ,'Village of Fraser Lake'                               ),
('Municipality'                    ,'LGMV_FRUITVALE'           ,'Village of Fruitvale'                                 ),
('Municipality'                    ,'LGMV_GOLD_RIVER'          ,'Village of Gold River'                                ),
('Municipality'                    ,'LGMV_GRANISLE'            ,'Village of Granisle'                                  ),
('Municipality'                    ,'LGMV_HARRISON_HOT_SPRINGS','Village of Harrison Hot Springs'                      ),
('Municipality'                    ,'LGMV_HAZELTON'            ,'Village of Hazelton'                                  ),
('Municipality'                    ,'LGMV_KASLO'               ,'Village of Kaslo'                                     ),
('Municipality'                    ,'LGMV_KEREMEOS'            ,'Village of Keremeos'                                  ),
('Municipality'                    ,'LGMV_LIONS_BAY'           ,'Village of Lions Bay'                                 ),
('Municipality'                    ,'LGMV_LUMBY'               ,'Village of Lumby'                                     ),
('Municipality'                    ,'LGMV_LYTTON'              ,'Village of Lytton'                                    ),
('Municipality'                    ,'LGMV_MASSET'              ,'Village of Masset'                                    ),
('Municipality'                    ,'LGMV_MCBRIDE'             ,'Village of McBride'                                   ),
('Municipality'                    ,'LGMV_MIDWAY'              ,'Village of Midway'                                    ),
('Municipality'                    ,'LGMV_MONTROSE'            ,'Village of Montrose'                                  ),
('Municipality'                    ,'LGMV_NAKUSP'              ,'Village of Nakusp'                                    ),
('Municipality'                    ,'LGMV_NEW_DENVER'          ,'Village of New Denver'                                ),
('Municipality'                    ,'LGMV_PEMBERTON'           ,'Village of Pemberton'                                 ),
('Municipality'                    ,'LGMV_PORT_ALICE'          ,'Village of Port Alice'                                ),
('Municipality'                    ,'LGMV_PORT_CLEMENTS'       ,'Village of Port Clements'                             ),
('Municipality'                    ,'LGMV_POUCE_COUPE'         ,'Village of Pouce Coupe'                               ),
('Municipality'                    ,'LGMV_RADIUM_HOT_SPRINGS'  ,'Village of Radium Hot Springs'                        ),
('Municipality'                    ,'LGMV_SALMO'               ,'Village of Salmo'                                     ),
('Municipality'                    ,'LGMV_SAYWARD'             ,'Village of Sayward'                                   ),
('Municipality'                    ,'LGMV_SILVERTON'           ,'Village of Silverton'                                 ),
('Municipality'                    ,'LGMV_SLOCAN'              ,'Village of Slocan'                                    ),
('Municipality'                    ,'LGMV_TAHSIS'              ,'Village of Tahsis'                                    ),
('Municipality'                    ,'LGMV_TELKWA'              ,'Village of Telkwa'                                    ),
('Municipality'                    ,'LGMV_VALEMOUNT'           ,'Village of Valemount'                                 ),
('Municipality'                    ,'LGMV_WARFIELD'            ,'Village of Warfield'                                  ),
('Municipality'                    ,'LGMV_ZEBALLOS'            ,'Village of Zeballos'                                  ),
('Other'                           ,'LGNILTA_ISLANDS'          ,'Islands Trust'                                        ),
('Other'                           ,'LGNILTA_SALT_SPRING'      ,'Salt Spring Island Local Trust Area'                  ),
('Other'                           ,'LGPBC_BC_PARKS'           ,'BC Parks'                                             ),
('Regional District Electoral Area','LGRD_ALBERNI_CLAYOQUOT'   ,'Regional District of Alberni-Clayoquot'               ),
('Regional District Electoral Area','LGRD_ATLIN'               ,'Atlin Community Improvement District'                 ),
('Regional District Electoral Area','LGRD_BULKLEY_NECHAKO'     ,'Regional District of Bulkley-Nechako'                 ),
('Regional District Electoral Area','LGRD_CAPITAL'             ,'Capital Regional District'                            ),
('Regional District Electoral Area','LGRD_CARIBOO'             ,'Cariboo Regional District'                            ),
('Regional District Electoral Area','LGRD_CENTRAL_COAST'       ,'Central Coast Regional District'                      ),
('Regional District Electoral Area','LGRD_CENTRAL_KOOTENAY'    ,'Regional District of Central Kootenay'                ),
('Regional District Electoral Area','LGRD_CENTRAL_OKANAGAN'    ,'Regional District of Central Okanagan'                ),
('Regional District Electoral Area','LGRD_COLUMBIA_SHUSWAP'    ,'Columbia Shuswap Regional District'                   ),
('Regional District Electoral Area','LGRD_COMOX_VALLEY'        ,'Comox Valley Regional District'                       ),
('Regional District Electoral Area','LGRD_COWICHAN_VALLEY'     ,'Cowichan Valley Regional District'                    ),
('Regional District Electoral Area','LGRD_EAST_KOOTENAY'       ,'Regional District of East Kootenay'                   ),
('Regional District Electoral Area','LGRD_FRASER_FORT_GEORGE'  ,'Regional District of Fraser-Fort George'              ),
('Regional District Electoral Area','LGRD_FRASER_VALLEY'       ,'Fraser Valley Regional District'                      ),
('Regional District Electoral Area','LGRD_KITIMAT_STIKINE'     ,'Regional District of Kitimat-Stikine'                 ),
('Regional District Electoral Area','LGRD_KOOTENAY_BOUNDARY'   ,'Regional District of Kootenay Boundary'               ),
('Regional District Electoral Area','LGRD_METRO_VANCOUVER'     ,'Metro Vancouver Regional District'                    ),
('Regional District Electoral Area','LGRD_MOUNT_WADDINGTON'    ,'Regional District of Mount Waddington'                ),
('Regional District Electoral Area','LGRD_NANAIMO'             ,'Regional District of Nanaimo'                         ),
('Regional District Electoral Area','LGRD_NORTH_COAST'         ,'North Coast Regional District'                        ),
('Regional District Electoral Area','LGRD_NORTH_OKANAGAN'      ,'Regional District of North Okanagan'                  ),
('Regional District Electoral Area','LGRD_OKANAGAN_SIMILKAMEEN','Regional District of Okanagan-Similkameen'            ),
('Regional District Electoral Area','LGRD_PEACE_RIVER'         ,'Peace River Regional District'                        ),
('Regional District Electoral Area','LGRD_QATHET'              ,'qathet Regional District'                             ),
('Regional District Electoral Area','LGRD_SQUAMISH_LILLOOET'   ,'Squamish-Lillooet Regional District'                  ),
('Regional District Electoral Area','LGRD_STRATHCONA'          ,'Strathcona Regional District'                         ),
('Regional District Electoral Area','LGRD_SUNSHINE_COAST'      ,'Sunshine Coast Regional District'                     ),
('Regional District Electoral Area','LGRD_THOMPSON_NICOLA'     ,'Thompson-Nicola Regional District'                    ),
('First Nations Community'         ,'LGXFN_ADAMS_LAKE'         ,'Adams Lake Indian Band'                               ),
('First Nations Community'         ,'LGXFN_AHOUSAHT'           ,'Ahousaht First Nation'                                ),
('First Nations Community'         ,'LGXFN_AITCHELITZ'         ,'Aitchelitz Band'                                      ),
('First Nations Community'         ,'LGXFN_?AKISQ_NUK'         ,'?Akisq''nuk First Nation'                             ),
('First Nations Community'         ,'LGXFN_?AQAM'              ,'?aqam'                                                ),
('First Nations Community'         ,'LGXFN_ASHCROFT'           ,'Ashcroft Indian Band'                                 ),
('First Nations Community'         ,'LGXFN_BINCHE_WHUT_EN'     ,'Binche Whut''en First Nation'                         ),
('First Nations Community'         ,'LGXFN_BLUEBERRY_RIVER'    ,'Blueberry River First Nation'                         ),
('First Nations Community'         ,'LGXFN_BONAPARTE'          ,'Bonaparte First Nation'                               ),
('First Nations Community'         ,'LGXFN_BOOTHROYD'          ,'Boothroyd Indian Band'                                ),
('First Nations Community'         ,'LGXFN_BOSTON_BAR'         ,'Boston Bar First Nation'                              ),
('First Nations Community'         ,'LGXFN_CANIM_LAKE'         ,'Canim Lake Indian Band (Tsq''escen’)'                 ),
('First Nations Community'         ,'LGXFN_CAYOOSE_CREEK'      ,'Cayoose Creek Band (Sekw''el''was)'                   ),
('First Nations Community'         ,'LGXFN_CHAWATHIL'          ,'Chawathil Band'                                       ),
('First Nations Community'         ,'LGXFN_CHEAM'              ,'Cheam First Nation'                                   ),
('First Nations Community'         ,'LGXFN_CHESLATTA'          ,'Cheslatta Indian Band'                                ),
('First Nations Community'         ,'LGXFN_COLDWATER'          ,'Coldwater Indian Band'                                ),
('First Nations Community'         ,'LGXFN_COOKS_FERRY'        ,'Cook''s Ferry Indian Band'                            ),
('First Nations Community'         ,'LGXFN_COWICHAN'           ,'Cowichan Tribes'                                      ),
('First Nations Community'         ,'LGXFN_DA_NAXDA_XW'        ,'Da''naxda''xw First Nation'                           ),
('First Nations Community'         ,'LGXFN_DEASE_RIVER'        ,'Dease River Band Council'                             ),
('First Nations Community'         ,'LGXFN_DITIDAHT'           ,'Ditidaht First Nation'                                ),
('First Nations Community'         ,'LGXFN_DOIG_RIVER'         ,'Doig River First Nation'                              ),
('First Nations Community'         ,'LGXFN_DOUGLAS'            ,'Douglas First Nation (Xa’xtsa)'                       ),
('First Nations Community'         ,'LGXFN_DZAWADA_ENUXW'      ,'Dzawada''enuxw First Nation'                          ),
('First Nations Community'         ,'LGXFN_EHATTESAHT'         ,'Ehattesaht First Nation'                              ),
('First Nations Community'         ,'LGXFN_?ESDILAGH'          ,'?Esdilagh First Nation'                               ),
('First Nations Community'         ,'LGXFN_ESK_ETEMC'          ,'Esk''etemc First Nation'                              ),
('First Nations Community'         ,'LGXFN_FORT_NELSON'        ,'Fort Nelson First Nation'                             ),
('First Nations Community'         ,'LGXFN_GITANMAAX'          ,'Gitanmaax Band Council'                               ),
('First Nations Community'         ,'LGXFN_GITANYOW'           ,'Gitanyow Hereditary Chiefs'                           ),
('First Nations Community'         ,'LGXFN_GITGA_AT'           ,'Gitga''at First Nation'                               ),
('First Nations Community'         ,'LGXFN_GITSEGUKLA'         ,'Gitsegukla Indian Band (Kitsegugkla)'                 ),
('First Nations Community'         ,'LGXFN_GITWANGAK'          ,'Gitwangak Band Council (Kitwanga)'                    ),
('First Nations Community'         ,'LGXFN_GITXAALA'           ,'Gitxaala Nation (Kitkatla)'                           ),
('First Nations Community'         ,'LGXFN_GLEN_VOWELL'        ,'Glen Vowell Indian Band (Sik-e-Dakh)'                 ),
('First Nations Community'         ,'LGXFN_GWA_SALA_NAKWAXDAXW','Gwa''sala-''Nakwaxda''xw Nation'                      ),
('First Nations Community'         ,'LGXFN_GWAWAENUK'          ,'Gwawaenuk Tribe'                                      ),
('First Nations Community'         ,'LGXFN_HAGWILGET'          ,'Hagwilget Village Council'                            ),
('First Nations Community'         ,'LGXFN_HAISLA'             ,'Haisla Nation'                                        ),
('First Nations Community'         ,'LGXFN_HALALT'             ,'Halalt First Nation'                                  ),
('First Nations Community'         ,'LGXFN_HALFWAY_RIVER'      ,'Halfway River First Nations'                          ),
('First Nations Community'         ,'LGXFN_HEILTSUK'           ,'Heiltsuk Nation'                                      ),
('First Nations Community'         ,'LGXFN_HESQUIAHT'          ,'Hesquiaht First Nation'                               ),
('First Nations Community'         ,'LGXFN_HIGH_BAR'           ,'High Bar First Nation'                                ),
('First Nations Community'         ,'LGXFN_HOMALCO'            ,'Homalco (Xwemalhkwu) Indian Band'                     ),
('First Nations Community'         ,'LGXFN_HUPA_ASATH'         ,'Hupa¢asath First Nation'                              ),
('First Nations Community'         ,'LGXFN_ISKUT'              ,'Iskut First Nation'                                   ),
('First Nations Community'         ,'LGXFN_KANAKA'             ,'Kanaka Bar Indian Band'                               ),
('First Nations Community'         ,'LGXFN_KATZIE'             ,'Katzie First Nation'                                  ),
('First Nations Community'         ,'LGXFN_KISPIOX'            ,'Kispiox Band Council'                                 ),
('First Nations Community'         ,'LGXFN_KITASOO_XAI_XAIS'   ,'Kitasoo/Xai''xais Band Council (Klemtu)'              ),
('First Nations Community'         ,'LGXFN_KITSELAS'           ,'Kitselas First Nation'                                ),
('First Nations Community'         ,'LGXFN_KITSUMKALUM'        ,'Kitsumkalum First Nation'                             ),
('First Nations Community'         ,'LGXFN_KLAHOOSE'           ,'Klahoose First Nation'                                ),
('First Nations Community'         ,'LGXFN_K_OMOKS'            ,'K’ómoks First Nation'                                 ),
('First Nations Community'         ,'LGXFN_KWADACHA'           ,'Kwadacha Nation'                                      ),
('First Nations Community'         ,'LGXFN_KWAKIUTL'           ,'Kwakiutl Indian Band'                                 ),
('First Nations Community'         ,'LGXFN_KWANTLEN'           ,'Kwantlen First Nation'                                ),
('First Nations Community'         ,'LGXFN_KWAW_KWAW_APILT'    ,'Kwaw-kwaw-Apilt First Nation'                         ),
('First Nations Community'         ,'LGXFN_KWIKWASUT_INUXW_HAX','Kwikwasut''inuxw Haxwa''mis First Nation'             ),
('First Nations Community'         ,'LGXFN_KWIKWETLEM'         ,'Kwikwetlem First Nation'                              ),
('First Nations Community'         ,'LGXFN_LAKE_BABINE'        ,'Lake Babine Nation'                                   ),
('First Nations Community'         ,'LGXFN_LAX_KW_ALAAMS'      ,'Lax Kw''alaams Indian Band'                           ),
('First Nations Community'         ,'LGXFN_LEQ_A_MEL'          ,'Leq''a:mel First Nation (Lakahahmen)'                 ),
('First Nations Community'         ,'LGXFN_LHEIDLI_T_ENNEH'    ,'Lheidli T''enneh First Nation'                        ),
('First Nations Community'         ,'LGXFN_LHOOSK_UZ_DENE'     ,'Lhoosk''uz Dene'' Government Administration (Kluskus)'),
('First Nations Community'         ,'LGXFN_LHTAKO_DENE'        ,'Lhtako Dene Nation'                                   ),
('First Nations Community'         ,'LGXFN_LIARD'              ,'Liard First Nation'                                   ),
('First Nations Community'         ,'LGXFN_LIL_WAT'            ,'Lil''wat Nation'                                      ),
('First Nations Community'         ,'LGXFN_LOWER_KOOTENAY'     ,'Lower Kootenay Indian Band (Yaqan nu?kiy)'            ),
('First Nations Community'         ,'LGXFN_LOWER_NICOLA'       ,'Lower Nicola Indian Band'                             ),
('First Nations Community'         ,'LGXFN_LOWER_SIMILKAMEEN'  ,'Lower Similkameen Indian Band'                        ),
('First Nations Community'         ,'LGXFN_LYACKSON'           ,'Lyackson First Nation'                                ),
('First Nations Community'         ,'LGXFN_LYTTON'             ,'Lytton First Nation'                                  ),
('First Nations Community'         ,'LGXFN_MALAHAT'            ,'Malahat First Nation'                                 ),
('First Nations Community'         ,'LGXFN_MATSQUI'            ,'Matsqui First Nation'                                 ),
('First Nations Community'         ,'LGXFN_MCLEOD_LAKE'        ,'McLeod Lake Indian Band'                              ),
('First Nations Community'         ,'LGXFN_METLAKATLA'         ,'Metlakatla First Nation'                              ),
('First Nations Community'         ,'LGXFN_MOWACHAHT_MUCHALAHT','Mowachaht/Muchalaht First Nation'                     ),
('First Nations Community'         ,'LGXFN_MUSQUEAM'           ,'Musqueam Indian Band'                                 ),
('First Nations Community'         ,'LGXFN_NADLEH_WHUTEN'      ,'Nadleh Whuten Band'                                   ),
('First Nations Community'         ,'LGXFN_NAK_AZDLI_WHUT_EN'  ,'Nak''azdli Whut''en'                                  ),
('First Nations Community'         ,'LGXFN_NAMGIS'             ,'‘Namgis First Nation'                                 ),
('First Nations Community'         ,'LGXFN_NANOOSE'            ,'Nanoose First Nation (Snaw-naw-as)'                   ),
('First Nations Community'         ,'LGXFN_NAZKO'              ,'Nazko First Nation'                                   ),
('First Nations Community'         ,'LGXFN_NEE_TAHI_BUHN'      ,'Nee-Tahi-Buhn Band'                                   ),
('First Nations Community'         ,'LGXFN_NESKONLITH'         ,'Neskonlith Indian Band'                               ),
('First Nations Community'         ,'LGXFN_NISGA_A'            ,'Nisga''a Nation'                                      ),
('First Nations Community'         ,'LGXFN_NOOAITCH'           ,'Nooaitch Indian Band'                                 ),
('First Nations Community'         ,'LGXFN_N_QUATQUA'          ,'N''Quatqua First Nation'                              ),
('First Nations Community'         ,'LGXFN_NUCHATLAHT'         ,'Nuchatlaht First Nation'                              ),
('First Nations Community'         ,'LGXFN_NUXALK'             ,'Nuxalk Nation'                                        ),
('First Nations Community'         ,'LGXFN_OKANAGAN'           ,'Okanagan Indian Band'                                 ),
('First Nations Community'         ,'LGXFN_OLD_MASSETT'        ,'Old Massett Village Council'                          ),
('First Nations Community'         ,'LGXFN_OREGON_JACK_CREEK'  ,'Oregon Jack Creek Band'                               ),
('First Nations Community'         ,'LGXFN_OSOYOOS'            ,'Osoyoos Indian Band'                                  ),
('First Nations Community'         ,'LGXFN_PACHEEDAHT'         ,'Pacheedaht First Nation'                              ),
('First Nations Community'         ,'LGXFN_PAUQUACHIN'         ,'Pauquachin First Nation'                              ),
('First Nations Community'         ,'LGXFN_PENELAKUT'          ,'Penelakut Tribe'                                      ),
('First Nations Community'         ,'LGXFN_PENTICTON'          ,'Penticton Indian Band'                                ),
('First Nations Community'         ,'LGXFN_PETERS'             ,'Peters Band'                                          ),
('First Nations Community'         ,'LGXFN_POPKUM'             ,'Popkum Indian Band'                                   ),
('First Nations Community'         ,'LGXFN_PROPHET_RIVER'      ,'Prophet River First Nation'                           ),
('First Nations Community'         ,'LGXFN_QUALICUM'           ,'Qualicum First Nation'                                ),
('First Nations Community'         ,'LGXFN_QUATSINO'           ,'Quatsino First Nation'                                ),
('First Nations Community'         ,'LGXFN_SAIK_UZ'            ,'Saik''uz First Nation'                                ),
('First Nations Community'         ,'LGXFN_SAMAHQUAM'          ,'Samahquam First Nation'                               ),
('First Nations Community'         ,'LGXFN_SAULTEAU'           ,'Saulteau First Nations'                               ),
('First Nations Community'         ,'LGXFN_SC_IANEW'           ,'Sc''ianew First Nation'                               ),
('First Nations Community'         ,'LGXFN_SEMIAHMOO'          ,'Semiahmoo First Nation'                               ),
('First Nations Community'         ,'LGXFN_SHACKAN'            ,'Shackan Indian Band'                                  ),
('First Nations Community'         ,'LGXFN_SHISHALH'           ,'shíshálh Nation'                                      ),
('First Nations Community'         ,'LGXFN_SHUSWAP'            ,'Shuswap Band'                                         ),
('First Nations Community'         ,'LGXFN_SHXWHA_Y'           ,'Shxwhá:y Village'                                     ),
('First Nations Community'         ,'LGXFN_SHXW_OW_HAMEL'      ,'Shxw''ow''hamel First Nation'                         ),
('First Nations Community'         ,'LGXFN_SIMPCW'             ,'Simpcw First Nation'                                  ),
('First Nations Community'         ,'LGXFN_SISKA'              ,'Siska Indian Band'                                    ),
('First Nations Community'         ,'LGXFN_SKATIN'             ,'Skatin Nations (Skookumchuck)'                        ),
('First Nations Community'         ,'LGXFN_SKAWAHLOOK_SQEWALXW','Skawahlook / Sq’ewá:lxw First Nation'                 ),
('First Nations Community'         ,'LGXFN_SKEETCHESTN'        ,'Skeetchestn Indian Band'                              ),
('First Nations Community'         ,'LGXFN_SKIDEGATE'          ,'Skidegate Band Council'                               ),
('First Nations Community'         ,'LGXFN_SKIN_TYEE'          ,'Skin Tyee Band'                                       ),
('First Nations Community'         ,'LGXFN_SKOWKALE'           ,'Skowkale First Nation'                                ),
('First Nations Community'         ,'LGXFN_SKUPPAH'            ,'Skuppah Indian Band'                                  ),
('First Nations Community'         ,'LGXFN_SKWAH'              ,'Skwah First Nation'                                   ),
('First Nations Community'         ,'LGXFN_SKWELAX_TE_SECWEPEM','Skwelax te Secwepemcelecw'                            ),
('First Nations Community'         ,'LGXFN_SNUNEYMUXW'         ,'Snuneymuxw First Nation'                              ),
('First Nations Community'         ,'LGXFN_SONGHEES'           ,'Songhees Nation'                                      ),
('First Nations Community'         ,'LGXFN_SOOWAHLIE'          ,'Soowahlie Indian Band'                                ),
('First Nations Community'         ,'LGXFN_SPLATSIN'           ,'Splatsin Band'                                        ),
('First Nations Community'         ,'LGXFN_SPUZZUM'            ,'Spuzzum (Spô’zêm) First Nation'                       ),
('First Nations Community'         ,'LGXFN_SQ_EWLETS'          ,'Sq''éwlets First Nation'                              ),
('First Nations Community'         ,'LGXFN_SQ_EWQEL'           ,'Sq’éwqel (Seabird Island Band)'                       ),
('First Nations Community'         ,'LGXFN_SQUAMISH'           ,'Squamish Nation'                                      ),
('First Nations Community'         ,'LGXFN_SQUIALA'            ,'Squiala First Nation'                                 ),
('First Nations Community'         ,'LGXFN_STELLAT_EN'         ,'Stellat''en First Nation'                             ),
('First Nations Community'         ,'LGXFN_STS_AILES'          ,'Sts''ailes Nation'                                    ),
('First Nations Community'         ,'LGXFN_STSWECEM_C_XGAT_TEM','Stswecem’c Xgat’tem First Nation'                     ),
('First Nations Community'         ,'LGXFN_STZ_UMINUS'         ,'Stz''uminus First Nation'                             ),
('First Nations Community'         ,'LGXFN_SUMAS'              ,'Sumas First Nation'                                   ),
('First Nations Community'         ,'LGXFN_TAHLTAN'            ,'Tahltan Band'                                         ),
('First Nations Community'         ,'LGXFN_TAKLA'              ,'Takla Nation'                                         ),
('First Nations Community'         ,'LGXFN_TAKU_RIVER_TLINGIT' ,'Taku River Tlingit First Nation'                      ),
('First Nations Community'         ,'LGXFN_T_IT_Q_ET'          ,'T''it''q''et'                                         ),
('First Nations Community'         ,'LGXFN_TK_EMLUPS_TE_SECWEP','Tk''emlúps te Secwépemc'                              ),
('First Nations Community'         ,'LGXFN_TLA_O_QUI_AHT'      ,'Tla-o-qui-aht First Nation'                           ),
('First Nations Community'         ,'LGXFN_TLATLASIKWALA'      ,'Tlatlasikwala'                                        ),
('First Nations Community'         ,'LGXFN_TL_AZT_EN'          ,'Tl''azt''en Nation'                                   ),
('First Nations Community'         ,'LGXFN_TL_ETINQOX'         ,'Tl''etinqox Government Office'                        ),
('First Nations Community'         ,'LGXFN_TL_ETINQOX_T_IN'    ,'Tl''etinqox-t''in Government Office'                  ),
('First Nations Community'         ,'LGXFN_TLOWITSIS'          ,'Tlowitsis Nation'                                     ),
('First Nations Community'         ,'LGXFN_TOBACCO_PLAINS'     ,'Tobacco Plains Indian Band'                           ),
('First Nations Community'         ,'LGXFN_TOOSEY'             ,'Toosey Indian Band (Tl''esqox)'                       ),
('First Nations Community'         ,'LGXFN_TSAL_ALH'           ,'Tsal''alh'                                            ),
('First Nations Community'         ,'LGXFN_TSARTLIP'           ,'Tsartlip First Nation'                                ),
('First Nations Community'         ,'LGXFN_TSAWOUT'            ,'Tsawout First Nation'                                 ),
('First Nations Community'         ,'LGXFN_TSAWWASSEN'         ,'Tsawwassen First Nation'                              ),
('First Nations Community'         ,'LGXFN_TSAY_KEH_DENE'      ,'Tsay Keh Dene'                                        ),
('First Nations Community'         ,'LGXFN_TSESHAHT'           ,'Tseshaht First Nation'                                ),
('First Nations Community'         ,'LGXFN_TSEYCUM'            ,'Tseycum First Nation'                                 ),
('First Nations Community'         ,'LGXFN_TSIDELDEL'          ,'Tŝideldel First Nation'                               ),
('First Nations Community'         ,'LGXFN_TS_IL_KAZ_KOH'      ,'Ts’il Kaz Koh First Nation'                           ),
('First Nations Community'         ,'LGXFN_TS_KW_AYLAXW'       ,'Ts''kw''aylaxw First Nation'                          ),
('First Nations Community'         ,'LGXFN_TSLEIL_WAUTUTH'     ,'Tsleil-Waututh Nation'                                ),
('First Nations Community'         ,'LGXFN_T_SOU_KE'           ,'T''sou-ke Nation'                                     ),
('First Nations Community'         ,'LGXFN_TSQ_ESCEN'          ,'Tsq''escen'' First Nation'                            ),
('First Nations Community'         ,'LGXFN_TS_UUBAA_ASATX'     ,'Ts''uubaa-asatx'                                      ),
('First Nations Community'         ,'LGXFN_TZEACHTEN'          ,'Tzeachten First Nation'                               ),
('First Nations Community'         ,'LGXFN_ULKATCHO'           ,'Ulkatcho First Nation'                                ),
('First Nations Community'         ,'LGXFN_UNION_BAR'          ,'Union Bar Indian Band'                                ),
('First Nations Community'         ,'LGXFN_UPPER_NICOLA'       ,'Upper Nicola Band'                                    ),
('First Nations Community'         ,'LGXFN_UPPER_SIMILKAMEEN'  ,'Upper Similkameen Indian Band'                        ),
('First Nations Community'         ,'LGXFN_WESTBANK'           ,'Westbank First Nation'                                ),
('First Nations Community'         ,'LGXFN_WEST_MOBERLY'       ,'West Moberly First Nations'                           ),
('First Nations Community'         ,'LGXFN_WET_SUWET_EN'       ,'Wet''suwet''en First Nation'                          ),
('First Nations Community'         ,'LGXFN_WE_WAI_KAI'         ,'We Wai Kai Nation'                                    ),
('First Nations Community'         ,'LGXFN_WE_WAI_KUM'         ,'We Wai Kum First Nation'                              ),
('First Nations Community'         ,'LGXFN_WHISPERING_PINES_CL','Whispering Pines/Clinton Indian Band'                 ),
('First Nations Community'         ,'LGXFN_WILLIAMS_LAKE'      ,'Williams Lake First Nation'                           ),
('First Nations Community'         ,'LGXFN_WITSET'             ,'Witset First Nation'                                  ),
('First Nations Community'         ,'LGXFN_WUIKINUXV'          ,'Wuikinuxv First Nation'                               ),
('First Nations Community'         ,'LGXFN_XAT_SULL'           ,'Xat''sull First Nation'                               ),
('First Nations Community'         ,'LGXFN_XAXLI_P'            ,'Xaxli''p First Nation'                                ),
('First Nations Community'         ,'LGXFN_XENI_GWET_IN'       ,'Xeni Gwet''in First Nations Government'               ),
('First Nations Community'         ,'LGXFN_XWISTEN'            ,'Xwísten'                                              ),
('First Nations Community'         ,'LGXFN_YAKWEAKWIOOSE'      ,'Yakweakwioose First Nation'                           ),
('First Nations Community'         ,'LGXFN_YALE'               ,'Yale First Nation'                                    ),
('First Nations Community'         ,'LGXFN_YEKOOCHE'           ,'Yekooche First Nation'                                ),
('First Nations Community'         ,'LGXFN_YUNESIT_IN'         ,'Yunesit''in First Nation'                             ))
AS s (local_government_type, organization_cd, organization_nm)
) AS src
ON (tgt.organization_cd=UPPER(src.organization_cd))
WHEN matched and (
coalesce(tgt.is_active, false) != true or
tgt.organization_nm!=src.organization_nm or
tgt.organization_type!='LG' or
tgt.local_government_type!=src.local_government_type or
tgt.local_government_type is null)
THEN UPDATE SET
is_active = true,
organization_nm=src.organization_nm,
organization_type='LG',
local_government_type=src.local_government_type
WHEN NOT MATCHED
THEN INSERT (is_active, organization_type, organization_cd, organization_nm, local_government_type)
VALUES (true, 'LG', src.organization_cd, src.organization_nm, src.local_government_type);
