primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    size: 400Mi
  resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 250Mi
readReplicas:
  persistence:
    size: 400Mi
nameOverride: strdssdev
fullnameOverride: strdssdev