postgresql:
  image:
    tag: 16.3.0
primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    size: 800Mi
  resources:
    limits:
      cpu: 150m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 700Mi
  networkPolicy:
    enabled: false
readReplicas:
  persistence:
    size: 800Mi
nameOverride: strdsstest
fullnameOverride: strdsstest
annotations:
  haproxy.router.openshift.io/balance: roundrobin
  haproxy.router.openshift.io/disable_cookies: 'true'
  haproxy.router.openshift.io/timeout: 180s
commonLabels:
  DataClass: "Medium"