primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    size: 400Mi
  resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 250Mi
readReplicas:
  persistence:
    size: 400Mi
nameOverride: strdsstest
fullnameOverride: strdsstest
annotations:
  haproxy.router.openshift.io/balance: roundrobin
  haproxy.router.openshift.io/disable_cookies: 'true'
  haproxy.router.openshift.io/timeout: 180s
commonLabels:
  DataClass: "Medium"