primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    size: 200Mi
readReplicas:
  persistence:
    size: 200Mi
nameOverride: strdssdev
fullnameOverride: strdssdev