name: Deploy Prod Environment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    environment:
      name: prod
      url: https://prod-strdss.f4a30d-dev.apps.silver.devops.gov.bc.ca/

    steps:
    - uses: hmarr/debug-action@a701ed95a46e6f2fb0df25e1a558c16356fae35a
    - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      with:
        ref: main # one source of truth for CI/CD pipeline

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@9b79eb6d8ec51bce42cb4e77f0a174fc80cf3cb9
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: f4a30d-prod
        insecure_skip_tls_verify: true

    - name: Deploy apps with Helm chart
      run: |
        vtag=${{ github.ref_name }}
        make upgrade \
        NAMESPACE=f4a30d-prod \
        NAME=strdss-prod \
        ENV_NAME=prod \
        IMAGE_TAG_FRONTEND=${vtag//v} \
        IMAGE_TAG_BACKEND=${vtag//v} \
      working-directory: ./helm/main
