name: Deploy Dev

on:
  workflow_dispatch:
#   push:
#     tags:
#     - v*.*.*

env:
  JFROG_REGISTRY: artifacts.developer.gov.bc.ca
  IMAGE_NAME_FRONTEND: sf4a-strdss/strdss-frontend
  IMAGE_NAME_BACKEND: sf4a-strdss/strdss-backend

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
    environment:
      name: dev
      url: https://dev-strdata.apps.silver.devops.gov.bc.ca/

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1.3
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: f4a30d-dev
        insecure_skip_tls_verify: true

    - name: Log in to JFrog Artifactory
      uses: docker/login-action@v1
      with:
        registry: artifacts.developer.gov.bc.ca
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}

    - name: Deploy apps with Helm chart
      run: |
        docker login artifacts.developer.gov.bc.ca -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }}
        make upgrade \
        NAMESPACE=f4a30d-dev \
        NAME=strdss-dev \
        ENV_NAME=dev \
        IMAGE_TAG_FRONTEND=latest \
        IMAGE_TAG_BACKEND=latest \
      working-directory: ./helm/main
